smithy-lang/smithy-swift

gradle.properties
Upgrade smithy to 1.9.1 to 1.10.0
Corresponding:
https://github.com/awslabs/aws-sdk-swift/pull/377
=> chore: upgrade smithy to 1.10.0

Packages/ClientRuntime/Sources/Networking/Http/Middlewares/ContentMD5Middleware.swift, Packages/SmithyTestUtil/Sources/RequestTestUtil/HttpRequestTestBase.swift, gradle.properties, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ClientRuntimeTypes.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolClientGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestRequestGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentMD5Middleware.kt
Updating smithy from 1.10.0 to 1.11.0
Corresponding:
https://github.com/awslabs/aws-sdk-swift/pull/378
=> chore: Upgrade smithy to 1.11.0

Packages/ClientRuntime/Sources/Middleware/NoopHandler.swift, Packages/ClientRuntime/Sources/Middleware/OperationStack.swift, Packages/ClientRuntime/Sources/Middleware/PresignerShimHandler.swift
Figured out an approach to get the request prior to sending it to the SDKHandler.  Capturing this code in a draft pr, and will build on top of it.
=> feat: foundational presigner components

smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ClientRuntimeTypes.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/CodegenVisitor.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/core/CodegenContext.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpBindingProtocolGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolClientGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/MiddlewareExecutionGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/ProtocolGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/SwiftIntegration.kt, smithy-swift-codegen/src/test/kotlin/HttpProtocolClientGeneratorTests.kt
Corresponding:
https://github.com/awslabs/aws-sdk-swift/pull/389
=> feat: support for generated presigner

smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ServiceGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpBindingProtocolGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolClientGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/ProtocolGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentMD5Middleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentTypeMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/OperationInputBodyMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/OperationInputHeadersMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/OperationInputQueryItemMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareExecutionGenerator.kt, smithy-swift-codegen/src/test/kotlin/HttpProtocolClientGeneratorTests.kt
Promoting various middlewares to fully fledged classes :)
=> chore: update content type, input body/headers/queryitem

smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/IdempotencyTokenMiddlewareGenerator.kt, smithy-swift-codegen/src/test/kotlin/IdempotencyTokenTraitTests.kt, smithy-swift-codegen/src/test/resources/Isolated/idempotencyToken.smithy
Need to add unit test before i refactor this.
=> chore: add unit test for idempoency token trait

smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/CodegenVisitor.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolTestGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestRequestGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentLengthMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentMD5Middleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentTypeMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/DeserializeMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/LoggingMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/OperationInputBodyMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/OperationInputHeadersMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/OperationInputQueryItemMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareExecutionGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareRenderable.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/OperationMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/OperationMiddlewareGenerator.kt, smithy-swift-codegen/src/test/kotlin/HttpProtocolUnitTestRequestGeneratorTests.kt, smithy-swift-codegen/src/test/kotlin/mocks/MockHttpEC2QueryProtocolGenerator.kt, smithy-swift-codegen/src/test/kotlin/mocks/MockHttpRestJsonProtocolGenerator.kt, smithy-swift-codegen/src/test/kotlin/mocks/MockHttpRestXMLProtocolGenerator.kt
Corresponding:
https://github.com/awslabs/aws-sdk-swift/pull/397
=> chore: unify middleware between client and protocol codegen tests

smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpBindingProtocolGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpBindingResolver.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/ProtocolGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/protocols/core/StaticHttpBindingResolver.kt, smithy-swift-codegen/src/test/kotlin/HttpProtocolUnitTestRequestGeneratorTests.kt, smithy-swift-codegen/src/test/kotlin/mocks/MockHttpEC2QueryProtocolGenerator.kt
Corresponding:
https://github.com/awslabs/aws-sdk-swift/pull/400
=> fix: use correct content type

smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/LoggingMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareRenderable.kt
Simplifying protocol before adding complexity
corresponding pr:
https://github.com/awslabs/aws-sdk-swift/pull/401
=> chore: simplify MiddlewareRenderable

Package.swift
=> chore: update version of the crt

smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpBindingProtocolGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolClientGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestRequestGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentLengthMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentMD5Middleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentTypeMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/DeserializeMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/IdempotencyTokenMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/LoggingMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/OperationInputBodyMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/OperationInputHeadersMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/OperationInputQueryItemMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/OperationInputUrlPathMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareExecutionGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareRenderable.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/OperationMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/OperationMiddlewareGenerator.kt
corresponding:
https://github.com/awslabs/aws-sdk-swift/pull/411
=> chore: refactor remove MiddlewareRenderableExecutionContext and update interface

gradle/wrapper/gradle-wrapper.properties
corresponding:
https://github.com/awslabs/aws-sdk-swift/pull/415
=> chore: upgrade gradle to 7.2

Package.swift
Updates to latest released version of crt bindings.
=> chore: update to new version of crt

Packages/ClientRuntime/Sources/Networking/Http/HttpContext.swift, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpUrlPathMiddleware.kt, smithy-swift-codegen/src/test/kotlin/HttpUrlPathMiddlewareTests.kt
This closes https://github.com/awslabs/aws-sdk-swift/issues/423
=> fix: runtime bug fix

Packages/SmithyTestUtil/Sources/RequestTestUtil/HttpRequestTestBase.swift, Packages/SmithyTestUtil/Tests/RequestTestUtilTests/HttpRequestTestBaseTests.swift, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestRequestGenerator.kt, smithy-swift-codegen/src/test/kotlin/HttpProtocolUnitTestRequestGeneratorTests.kt, smithy-swift-codegen/src/test/kotlin/IsolatedHttpProtocolUnitTestRequestGeneratorTests.kt
=> chore: add support for resolvedHost for request tests

gradle.properties, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpBindingProtocolGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentLengthMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentTypeMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/OperationInputBodyMiddleware.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/handlers/MiddlewareShapeUtils.kt, smithy-swift-codegen/src/test/kotlin/HttpProtocolUnitTestRequestGeneratorTests.kt
Corresponding:
https://github.com/awslabs/aws-sdk-swift/pull/474
=> chore: upgrade to smithy 1.13.0

Package.swift
=> fix: update version of crt

Packages/ClientRuntime/Sources/Networking/Http/CRT/CRTClientEngine.swift, Packages/ClientRuntime/Sources/Networking/Http/Middlewares/ContentMD5Middleware.swift
=> chore: fix compiler warnings in clientruntime

gradle.properties
Corresponding:
https://github.com/awslabs/aws-sdk-swift/pull/482
=> chore: upgrade smithy to 1.13.1

Package.swift
=> chore: update ci to new version

Packages/ClientRuntime/Sources/Networking/Http/CRT/CRTClientEngine.swift, Packages/ClientRuntime/Sources/Networking/Http/CRT/SDKDefaultIO.swift, Packages/ClientRuntime/Sources/Retries/SDKRetryer.swift
This corrects a lifetime issue we had when multiple services are in use and attempting to use shared resources.
Corresponding PR: https://github.com/awslabs/aws-sdk-swift/pull/501
- [ X] Bug fix (non-breaking change which fixes an issue)
=> fix: changes to fix lifetime issues when multiple sdks are in use

Package.swift
=> chore: bump version dep on crt

build.gradle.kts, buildSrc/build.gradle.kts, gradle.properties, settings.gradle.kts, smithy-swift-codegen/build.gradle.kts
corresponding:
https://github.com/awslabs/aws-sdk-swift/pull/507
=> chore: update build system to remove hardcoded maven urls

Packages/ClientRuntime/Sources/Util/PlatformOperationSystemVersion.swift
corresponding:
https://github.com/awslabs/aws-sdk-swift/pull/516
=> chore: os version in useragent for foundation based OS

Packages/ClientRuntime/Sources/Logging/LogAgent.swift, Packages/ClientRuntime/Sources/Logging/SwiftLog+LogAgent.swift
Need to test this a bit more, but i'm pretty sure this will resolve:
https://github.com/awslabs/aws-sdk-swift/issues/518
=> fix: logging interface to wrap swift-log

Packages/ClientRuntime/Sources/PrimitiveTypeExtensions/String+Extensions.swift
Dependent on:
https://github.com/awslabs/aws-sdk-swift/pull/521
=> chore: Adding extension to strip first prefix from string

Package.swift
Update crt version in prep for release
=> fix: update crt version

Package.swift
=> fix: update version of CRT in prep for release

Package.swift
=> fix: upgrade crt version

smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareExecutionGenerator.kt
Corresponding PR: https://github.com/awslabs/aws-sdk-swift/pull/554
- [ x] New feature (non-breaking change which adds functionality)
=> fix: corresponding change for s3 put object presigned urls

Package.swift
Update version of the CRT in prep for release
=> fix: update version of the crt

Packages/ClientRuntime/Sources/Util/SwiftVersion.swift
Adding Swift 5.7 version to `swiftVersion` property which is added in Xcode 14.
=> Add Swift 5.7 to swiftVersion property

Package.swift
=> chore: bump aws-crt-swift version to 0.3.0

.github/workflows/continuous-integration.yml, .github/workflows/lint.yml
Remove Github CI & linter workflow filter for base branch, so that pushes to any open PR are tested & linted.
Allows for testing of changes to be merged into feature branches or other branches.
=> chore: Test all PRs regardless of base branch

Package.swift
=> chore: bump aws-crt-swift version to 0.3.1

smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentMD5Middleware.kt
this is temporary fix until we implement flexible checksum support
backlog: https://github.com/awslabs/aws-sdk-swift/issues/653
ContentMD5Middleware middleware is back in pipeline setup.
```swift
public func deleteObjects(input: DeleteObjectsInput) async throws -> DeleteObjectsOutputResponse
{
let context = ClientRuntime.HttpContextBuilder()
.withEncoder(value: encoder)
.withDecoder(value: decoder)
.withMethod(value: .post)
.withServiceName(value: serviceName)
.withOperation(value: "deleteObjects")
.withIdempotencyTokenGenerator(value: config.idempotencyTokenGenerator)
.withLogger(value: config.logger)
.withCredentialsProvider(value: config.credentialsProvider)
.withRegion(value: config.region)
.withSigningName(value: "s3")
.withSigningRegion(value: config.signingRegion)
var operation = …
```
=> fix: treat HttpChecksumRequiredTrait and HttpChecksumTrait same way

builder.json
This PR reverts a previous change that removed building CRT upstream. We're adding this back in now that we've fixed the compatibility issues. 
=> chore: Builds CRT upstream

smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/FoundationTypes.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/SwiftWriter.kt
=> Adds FoundationTypes and adds function to import individual types from modules

Package.swift
Counterpart: https://github.com/awslabs/aws-sdk-swift/pull/816
=> chore: bump aws-crt-swift to 0.5.4

gradle.properties
Fixes https://github.com/awslabs/aws-sdk-swift/issues/785
https://github.com/awslabs/aws-sdk-swift/pull/815
=> chore: bump smithy version to 1.27.0

Package.swift
=> chore: bump aws-crt-swift to 0.5.7

Package.swift
=> chore: bump aws-crt-swift to 0.6.0

Sources/ClientRuntime/Util/SwiftVersion.swift
[#884](https://github.com/awslabs/aws-sdk-swift/issues/884)
Adds handling for many two full future swift versions
=> fix: removes explicit erroring when compiling on a future swift version

Packages/ClientRuntime/Sources/Util/SwiftVersion.swift
* fix: removes explicit erroring when compiling on a future swift version
* Updates function names"
=> fix: removes explicit erroring when compiling on a future swift version (#528)

Sources/ClientRuntime/Pagination/PaginatorSequence.swift, Sources/ClientRuntime/Util/SwiftVersion.swift
Fixes various issues flagged by SwiftLint.
=> chore: Fix swiftlint violations

Package.swift
=> chore: pins xmlcoder version

.github/workflows/lint.yml
Updates version of SwiftLint used to latest available.
=> chore: Update Swiftlint to 0.52.3

Sources/ClientRuntime/Serialization/SerializationUtils/TimestampSerdeUtils.swift
Fixes a Swiftlint issue introduced with new Swiftlint.
=> chore: Fix Swiftlint issue

README.md
Some change since last release needed to allow build process to succeed.
=> chore: Change README

gradle.properties, smithy-swift-codegen/src/test/kotlin/TestUtils.kt
https://github.com/awslabs/aws-sdk-swift/issues/1037 (this Smithy update is a prereq for this issue)
Updates to latest Smithy version, to get latest Smithy features and goodness.
=> chore: Use Smithy 1.37.0

Package.swift
https://github.com/awslabs/aws-sdk-swift/issues/1154
Updates to aws-crt-swift 0.15.0 to get the latest fixes on CRT libraries.
=> chore: Update to aws-crt-swift 0.15.0

Package.swift
https://github.com/awslabs/aws-sdk-swift/issues/1204
Update aws-crt-swift dependency to 0.17.0.
=> fix: Update aws-crt-swift dependency to 0.17.0.

Sources/ClientRuntime/Networking/Http/CRT/CRTClientEngine.swift
https://github.com/awslabs/aws-sdk-swift/issues/1035
When pooling HTTP connections, the SDK currently shares connections among requests that are unique to that request's `Endpoint` structure.  Because `Endpoint` contains a lot of fields that are unrelated to where the connection is made (i.e. headers, path, query string, etc.), pooling by `Endpoint` results in almost every request being in its own pool.  This results in existing connections almost never being reused.
Per conversation with CRT, connections should be pooled together if they use the same scheme, host, and port.  A custom type is introduced that is used to store & reuse existing connection pool managers based on those fields alone.
Increased connection reuse seems to result in substantial performance improvements: integration …
=> fix: Pool HTTP connections based on scheme, host, and port

Package.swift
[#1271](https://github.com/awslabs/aws-sdk-swift/issues/1271), [#1273](https://github.com/awslabs/aws-sdk-swift/issues/1273)
=> chore: Update to aws-crt-swift 0.20.0

Package.swift, Sources/ClientRuntime/Networking/Http/CRT/CRTClientEngine.swift, Sources/ClientRuntime/Networking/Http/CRT/HTTP2Stream+ByteStream.swift, Sources/ClientRuntime/Networking/Http/Middlewares/ContentMD5Middleware.swift
=> chore: update to CRT 0.22.0

README.md
Whitespace change.  Intended to unblock build system.
=> chore: Empty commit

gradle.properties
https://github.com/awslabs/aws-sdk-swift/issues/1332
Update to use Smithy 1.44.0 (latest release).
=> chore: Update to Smithy 1.44.0

.github/workflows/lint.yml
https://github.com/awslabs/aws-sdk-swift/issues/1341
Update Swiftlint used on CI from 0.52.3 to 0.54.0.
=> chore: Update swiftlint to 0.54.0

Sources/ClientRuntime/Plugins/AuthSchemePlugin.swift, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/AuthSchemeResolverGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/SwiftWriter.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolServiceClient.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/Plugin.kt
=> feat: add AuthSchemePlugin

gradle.properties
=> chore: Bump Smithy version from 1.44.0 to 1.45.0

README.md
Whitespace change to allow automated release to continue.
=> chore: Whitespace-only change to allow release

smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ServiceGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/SwiftWriter.kt, smithy-swift-codegen/src/test/kotlin/StructureGeneratorTests.kt
- Explicitly order errors alphabetically in generated comments
- Handle unconditional extra spacing in deprecated shape message to be added conditionally
=> chore: Misc codegen fixes

Sources/ClientRuntime/Endpoints/ServiceEndpointMetadata.swift, Sources/ClientRuntime/Endpoints/SmithyEndpoint.swift, Sources/ClientRuntime/Plugins/DefaultClientPlugin.swift, Tests/ClientRuntimeTests/NetworkingTests/Http/MiddlewareTests/FlexibleChecksumsMiddlewareTests.swift
Eliminates a few compile warnings.
=> chore: Eliminate compile warnings in ClientRuntime and tests

Sources/SmithyRetries/DefaultRetryStrategy/DefaultRetryStrategy+Error.swift, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/SwiftWriter.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/events/MessageUnmarshallableGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/httpResponse/HTTPResponseBindingErrorGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/model/SymbolBuilder.kt
Companion PR: https://github.com/awslabs/aws-sdk-swift/pull/1528
https://github.com/awslabs/aws-sdk-swift/issues/1201
Downstream changes needed to accommodate upstream's `AWSClientRuntime.UnknownAWSHTTPServiceError` being changed to internal using `@_spi` tag.
=> feat!: Conceal unknown error type

Package.swift
https://github.com/awslabs/aws-sdk-swift/issues/1592
Publish SmithyTimestamps as a library for use by consumers outside smithy-swift.
=> chore: Publish SmithyTimestamps module

Package.swift
https://github.com/awslabs/aws-sdk-swift/issues/696
Update to latest aws-crt-swift (0.32.0) for updates needed for observability.
=> chore: Use aws-crt-swift 0.32.0

smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/DirectedSwiftCodegen.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/CustomDebugStringConvertibleGenerator.kt, smithy-swift-codegen/src/test/kotlin/CustomDebugStringConvertibleGeneratorTests.kt, smithy-swift-codegen/src/test/resources/custom-debug-string-convertible-generator-test.smithy
Quip: `Sensitive-listmap-members-investigation`
Companion PR in aws-sdk-swift for verifying CIs pass: https://github.com/awslabs/aws-sdk-swift/pull/1636
https://github.com/awslabs/aws-sdk-swift/issues/1632
=> fix: Widen sensitive trait check to nested members of list and map members.

smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/utils/AuthUtils.kt
Companion PR: https://github.com/awslabs/aws-sdk-swift/pull/1650
- Add util function for checking if auth scheme is supported or not to AuthUtils.
=> chore: Add utility function for checking auth scheme availability

Package.swift
- https://github.com/awslabs/aws-sdk-swift/issues/1651
=> fix: Add DocC dependency utility function to Package.swift

Package.swift
https://github.com/awslabs/aws-sdk-swift/issues/1664
Update to latest `aws-crt-swift` with support for EP2.0 OperationContextParams.
=> chore: Update aws-crt-swift to 0.33.0

.github/dependabot.yml
- https://github.com/awslabs/aws-sdk-swift/issues/1711
=> chore: Make dependabot run daily

smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/SmokeTestGenerator.kt
- Fix `orElse(null)` misuse
- Add ability to disable smoke test codegen by service name
- Fix bug where operations attached to the service's nested resource shape weren't getting their smoke tests generated properly.
=> fix: Smoke test codegen bug fix

.github/workflows/repo-sync.yml
=> chore: Update repo-sync.yml

Package.swift
Updates `aws-crt-swift` to latest version (0.42.0).
=> chore: Update to aws-crt-swift 0.42.0

Package.swift
Companion PR: https://github.com/awslabs/aws-sdk-swift/pull/1861
152
- The v0.43.0 of aws-crt-swift adds parsing for the new `[services]` section in AWS shared config file.
=> chore: Bump CRT version to 0.43.0

scripts/clean_project.sh
Adds a script that deletes caches & build products from the project.
=> chore: Add script for cleaning build products

Sources/ClientRuntime/Config/ClientConfigDefaultsProvider.swift
=> fix: change retryStrategyOptions name to avoid conflict

Package.swift
Update aws-crt-swift to 0.45.0 (0.45.0 includes support for `sigv4-s3express` request signing.)
=> chore: Update aws-crt-swift to 0.45.0

Package.swift
=> chore: bump crt version to 0.47.0

.github/workflows/continuous-integration.yml
Runs CI & downstream tests on Linux x86-64 and arm64.
=> chore: Run CI & downstreams on ARM linux

smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/DefaultHTTPProtocolCustomizations.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HTTPBindingProtocolGenerator.kt, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HTTPProtocolCustomizable.kt
=> fix: Generate CBOR smoke tests as AWS services

Package.swift, smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/PackageManifestGenerator.kt, smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/manifestanddocs/PackageManifestGeneratorTests.kt
=> chore: bump minimum macOS version to v12

Package.swift
=> fix: Pull in open-telemetry libraries on mac catalyst

Sources/ClientRuntime/Networking/Http/NIO/NIOHTTPClientConfiguration+HTTPClientConfiguration.swift
- Add extension on HTTPClient.Configuration to make instance from SDK HTTPClientConfiguration
=> Add basic configuration extension

Sources/ClientRuntime/Networking/Http/NIO/NIOHTTPClient.swift, Sources/ClientRuntime/Networking/Http/NIO/NIOHTTPClientTLSOptions.swift, Sources/ClientRuntime/Networking/Http/NIO/NIOHTTPClientTLSResolverUtils.swift, Tests/ClientRuntimeTests/NetworkingTests/Http/NIO/NIOHTTPClientTLSOptionsTests.swift
=> Add support for TLS configuration

gradle.properties
=> chore: bump to smithy 1.62
