- Packages/ClientRuntime/Sources/Middleware/OperationStack.swift
- Packages/ClientRuntime/Sources/Networking/Http/Middlewares/DeserializeMiddleware.swift
- Packages/ClientRuntime/Tests/MiddlewareTests/MiddlewareStackTests.swift
- gradle.properties
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ClientRuntimeTypes.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpBindingProtocolGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentLengthMiddleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/DeserializeMiddleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareExecutionGenerator.kt
- smithy-swift-codegen/src/test/kotlin/HttpProtocolClientGeneratorTests.kt
Removing addDefaultOperationMiddlewares
corresponding: https://github.com/awslabs/aws-sdk-swift/pull/394
> chore: remove addDefaultOperationMiddlewares

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentMD5Middleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareRenderable.kt
- smithy-swift-codegen/src/test/kotlin/ContentMd5MiddlewareTests.kt
- smithy-swift-codegen/src/test/resources/Isolated/contentmd5checksum.smithy
ContentMD5Middleware was not properly conforming to `MiddlewareRenderable` (well, it was but.. since there was a default impl  of `{}`, it was possible to call render on this middleware and render nothing) -- therefore in real code generated client, the ContentMD5Middleware was never getting properly rendered
This is a temporary fix before we revamp the interface.
> chore: fix contentmd5middleware to render properly

- Packages/ClientRuntime/Sources/Serialization/SerializationUtils/TimestampWrapperDecoder.swift
This closes https://github.com/awslabs/aws-sdk-swift/issues/390
Rest xml uses date time format with fractional seconds
- [x ] Bug fix (non-breaking change which fixes an issue)
> fix: date time to use fractional seconds

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolClientGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestRequestGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentLengthMiddleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentMD5Middleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/ContentTypeMiddleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/DeserializeMiddleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/IdempotencyTokenMiddleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/LoggingMiddleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/OperationInputBodyMiddleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/OperationInputHeadersMiddleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/OperationInputQueryItemMiddleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareExecutionGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareRenderable.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/OperationMiddleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/OperationMiddlewareGenerator.kt
This is one proposed way of allowing customers to override the sigv4 config for presigners.
Corresponding:
https://github.com/awslabs/aws-sdk-swift/pull/402
> feat: Expose sigv4 config for presigner

- Packages/ClientRuntime/Sources/PrimitiveTypeExtensions/URL+Extension.swift
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ClientRuntimeTypes.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareExecutionGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareRenderable.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/OperationMiddleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/OperationMiddlewareGenerator.kt
Corresponding:
https://github.com/awslabs/aws-sdk-swift/pull/407
> feat: Implement GET presigner for synthesizespeech

- Packages/ClientRuntime/Sources/PrimitiveTypeExtensions/Number+Extension.swift
- Packages/SmithyTestUtil/Sources/RequestTestUtil/MockSerializeStreamMiddleware.swift
- Packages/SmithyTestUtil/Sources/RequestTestUtil/MockStreamInput.swift
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolTestGenerator.kt
Corresponding PRs: https://github.com/awslabs/aws-crt-swift/pull/46 and https://github.com/awslabs/aws-sdk-swift/pull/421
> fix: test change needed to pass an import down to smithy swift

- Packages/ClientRuntime/Sources/Networking/Http/CRT/CRTClientEngine.swift
This fixes the tcp timeout for iOS/watchOS per the new SEP requirements. Corresponding PR: https://github.com/awslabs/aws-crt-swift/pull/56
- [x ] Bug fix (non-breaking change which fixes an issue)
> fix: tcp connection timeout

- Packages/ClientRuntime/Sources/Networking/Http/CRT/CRTClientEngine.swift
- Packages/ClientRuntime/Sources/Networking/Http/CRT/SDKDefaultIO.swift
This corrects an issue @royjit found where one thread was creating the logger and another was creating the event loop in the crt and trying to call the logger before it had been created (race condition). the same thread should be creating both resources so the logger should be moved into the shared io file to be created there with all other crt types.
> fix: Fixes an issue with creation of crt Logger

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/xml/MemberShapeDecodeXMLGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/xml/StructDecodeXMLGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/xml/UnionDecodeXMLGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/lang/ReservedWords.kt
- smithy-swift-codegen/src/test/kotlin/serde/xml/UnionEncodeXMLGenerationTests.kt
This PR fixes S3 compiler errors with decoding non optional associated values on enums. This additionally changes our decoding of enums with associated values from needing return statemetns everywhere to one switch statement based on the key in the container.
```swift
init(from decoder: Decoder) throws {
let containerValues = try decoder.container(keyedBy: CodingKeys.self)
let key = containerValues.allKeys.first
switch key {
case .empty:
self = .empty
case .domain:
let domain = try container.decode(
String.self,
forKey: .editing
)
self = .domain(domain)
case .port:
let port = try container.decode(
Int.self,
forKey: .port
)
self = .port(port)
default:
self = .sdkUnknown("")
}
}
```
By submitting this pull request, I confirm that my …
> fix: fixes s3 decode compiler errors

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/CodegenVisitor.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/StructureGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpBindingProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/HashableShapeTransformerTests.kt
- smithy-swift-codegen/src/test/kotlin/RecursiveShapeBoxerTests.kt
- smithy-swift-codegen/src/test/kotlin/SensitiveTraitGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/ServiceRenamesTests.kt
- smithy-swift-codegen/src/test/kotlin/StructDecodeGenerationTests.kt
- smithy-swift-codegen/src/test/kotlin/StructEncodeGenerationIsolatedTests.kt
- smithy-swift-codegen/src/test/kotlin/StructureGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/UnionDecodeGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/serde/awsjson11/NestedListEncodeJSONGenerationTests.kt
- smithy-swift-codegen/src/test/kotlin/serde/xml/EnumDecodeXMLGenerationTests.kt
- smithy-swift-codegen/src/test/kotlin/serde/xml/StructDecodeXMLGenerationTests.kt
This PR contains two fixes as suggested by Apple to decrease binary size:
- decrease usage of the word public where not needed
- decrease generation of CustomDebugStringConvertible Conformance where not needed.
For reference this takes Lambda down to 25.7 MB from 29.5 MB now.
Corresponding PR: https://github.com/awslabs/aws-sdk-swift/pull/539
> fix: shave off 4 mb from sdks

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/StructureGenerator.kt
- smithy-swift-codegen/src/test/kotlin/HashableShapeTransformerTests.kt
- smithy-swift-codegen/src/test/kotlin/RecursiveShapeBoxerTests.kt
- smithy-swift-codegen/src/test/kotlin/ServiceRenamesTests.kt
- smithy-swift-codegen/src/test/kotlin/StructEncodeGenerationIsolatedTests.kt
- smithy-swift-codegen/src/test/kotlin/StructureGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/serde/awsjson11/NestedListEncodeJSONGenerationTests.kt
This reverts one of the changes made in https://github.com/awslabs/smithy-swift/pull/403 that went too far in removing public modifiers needed by customers. One of them that was removed was not needed but one was. This puts that one back.
> fix: revert public modifier change

- Packages/ClientRuntime/Sources/Util/SwiftVersion.swift
smithy-swift (and thereby the AWSSwiftSDK) throw a compiler error when building with Swift 5.6
This is a quick fix that resolves the compiler error and doesn't break anything else based on manual testing.
Next step would be supporting Swift 5.6 language features, e.g. `any P`. That change should come in a subsequent feat PR so we can fix the existing issue quickly.
Side note: Swift 5.7 has been confirmed as the next major version. However If we want to keep this language version checking strategy going forward, it may make sense to switch to `> existing version` rather than `>= potential next version`. 
> fix: add Swift 5.6 case in swiftVersion property to resolve compiler error

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/StructureGenerator.kt
https://github.com/awslabs/aws-sdk-swift/issues/568
Structures with no members have no way to be initialised by consumers.
> Add a public initializer for structures with no members.

- Packages/ClientRuntime/Sources/Retries/Retryer.swift
- Packages/ClientRuntime/Sources/Retries/SDKRetryer.swift
this change eliminates a redundant call to releaseToken
Related: https://github.com/awslabs/aws-crt-swift/issues/66
> removes the redundant call for releaseToken

- Packages/ClientRuntime/Sources/Networking/Http/CRT/CRTClientEngine.swift
- Packages/ClientRuntime/Sources/Networking/Http/HttpClientEngine.swift
- Packages/ClientRuntime/Sources/Networking/Http/SdkHttpClient.swift
* creates nested actor named ConnectionPoolContainer in CRTClientEngine
* public functions were directed to the actor to manage connection pools
#423
Moves state management into an `actor` to make it thread-safe.
> fixes data race in CRTClientEngine

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/json/MemberShapeEncodeGenerator.kt
- smithy-swift-codegen/src/test/kotlin/ServiceRenamesTests.kt
- smithy-swift-codegen/src/test/kotlin/StructDecodeGenerationTests.kt
- smithy-swift-codegen/src/test/kotlin/StructEncodeGenerationTests.kt
- smithy-swift-codegen/src/test/kotlin/UnionEncodeGeneratorTests.kt
https://github.com/awslabs/aws-sdk-swift/issues/603
This change is required to unblock https://github.com/awslabs/aws-sdk-swift/pull/597 release. We need to look holistically to avoid this kind of conflict at other places where `Codable` and `Decodable` are implemented.
Before
```swift
extension IvsClientTypes.VideoConfiguration: Swift.Codable {
enum CodingKeys: Swift.String, Swift.CodingKey {
case avcLevel
case avcProfile
case codec
case encoder
case targetBitrate
case targetFramerate
case videoHeight
case videoWidth
}
public func encode(to encoder: Swift.Encoder) throws {
var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
if let avcLevel = avcLevel {
try encodeContainer.encode(avcLevel, forKey: .avcLevel)
}
if let avcProfile = avcProfile {
try …
```
> fix: use self to disambiguate between member and encoder param

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/PaginatorGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/SymbolVisitor.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/model/SymbolExt.kt
- smithy-swift-codegen/src/test/kotlin/PaginatorGeneratorTest.kt
https://github.com/awslabs/aws-sdk-swift/issues/606
https://github.com/awslabs/aws-sdk-swift/issues/605
This change addresses two problems
1. When pagination nested property is map instead of array. Currently, the SDK fails to compile https://github.com/awslabs/aws-sdk-swift/issues/606 Ex. APIGateway service. With this change, the nested map property is converted to array of (Key, Value) pair. This change is similar to Kotlin implementation [here](https://github.com/awslabs/smithy-kotlin/blob/910b61368ad126c2f751b3df79253530153aff6c/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/rendering/PaginatorGenerator.kt#L251)
2. The nested pagination property by design is accessible to public which it is not currently, this change makes it public. 
By submitting this …
> fix: convert map to array of entry for paginators

- gradle.properties
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ShapeValueGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/SwiftWriter.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/httpResponse/bindingTraits/HttpResponseTraitWithHttpPayload.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/handlers/HttpBodyMiddleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/model/NestedShapeTransformer.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/model/ShapeExt.kt
Upgrade to Smithy version 1.23
* Upgrade smithyVersion to 1.23.0 that adds support for IDL-2.0
* Avoid emitting the available attribute for shapes deprecated in the prelude, this will keep the output unchanged.
- Add the logic to support for enums shapes that now are their own type instead of being a trait over string shapes
- Fix the recursive logic to annotate shapes to avoid infinite recursion
> Updgrade 1.23

- Packages/ClientRuntime/Sources/Pagination/PaginatorSequence.swift
This fixes an open issue on the AWS Swift SDK repo awslabs/aws-sdk-swift#588.
* The `PaginatorSequence` struct does not return values if there is only one page of values (no pagination required).
* This is because of a code block that breaks the loop if the input page token and the page token in the API response are equal. But if there is only one page of values, then both input page token and page token in the API response would both be `nil`.
```swift
import AWSCloudWatchLogs
import AWSClientRuntime
let aws_config = AWSCredentialsProviderStaticConfig(
accessKey: "REPLACE_THIS",
secret: "REPLACE_THIS"
)
do {
let client_config = try CloudWatchLogsClient.CloudWatchLogsClientConfiguration(
region: "us-west-2",
credentialsProvider: AWSCredentialsProvider.fromStatic(aws_config)
)
let client = …
```
> PaginatorSequence should return values even if there is only one page of values

- smithy-swift-codegen/src/test/kotlin/EnumGeneratorTests.kt
- smithy-swift-codegen/src/test/resources/enum-shape-test.smithy
Adds a unit test that tests that we generate code correctly using the `enum` shape from IDL-2.0. This test complements the [previous pull request](https://github.com/awslabs/smithy-swift/pull/432) that added logic to support enum shapes from IDL-2.0.
> chore: add unit tests for IDL-2.0 enum shapes code generation

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/json/MemberShapeDecodeGenerator.kt
fixes https://github.com/awslabs/aws-sdk-swift/issues/564
fixes https://github.com/awslabs/aws-sdk-swift/issues/611
Codegen uses default values to generate the init for non-optional values eg. https://github.com/awslabs/aws-sdk-swift/blob/0.2.6/release/AWSSecretsManager/models/Models.swift#L4148 but while doing the deserialization, the member is considered as always present which is not true in service like AWSSecretsManager.
This change uses the the same default value is available to set the member when the response doesn't contain the field. To generate less code, codegen skips assigning `nil`.
Before
```swift
let rotationEnabledDecoded = try containerValues.decode(Swift.Bool.self, forKey: .rotationEnabled)
rotationEnabled = rotationEnabledDecoded
```
After
```swift
let …
```
> fix: use default value when deserializing non-optional members

- gradle.properties
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/PackageManifestGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/SwiftDelegator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/SwiftDependency.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/SymbolVisitor.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestResponseGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/httpResponse/HttpResponseHeaders.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/providers/HttpUrlPathProvider.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/formurl/MemberShapeEncodeFormURLGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/json/MemberShapeDecodeGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/json/MemberShapeEncodeGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/json/UnionDecodeGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/xml/MemberShapeDecodeXMLGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/xml/MemberShapeEncodeXMLGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/xml/StructEncodeXMLGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/model/SymbolExt.kt
- smithy-swift-codegen/src/test/kotlin/ServiceGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/StructureGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/SymbolProviderTest.kt
- smithy-swift-codegen/src/test/kotlin/TestUtils.kt
Change the way we compute the nullability of members. Before we were only looking at the box trait in the target type for the `box` trait and ignoring the trait on the member itself. See for instance the test `can read box trait from member` which has the following model:
```
namespace com.test
structure MyStruct {
@box
foo: MyFoo
}
long MyFoo
```
The code was incorrectly assuming that the `foo` member was not nullable. This change accounts for this by using the `NullableIndex` which correctly computes whether or not the member or the target type are nullable. This change in turn was also required in several places that were making the same mistake and assuming that computing the `Symbol` for the target and testing for `isBoxed()` was enough to know if the member is itself boxed.
After …
> fix: properly check if a member can be nullable

- Packages/ClientRuntime/Sources/Networking/Http/Headers.swift
- Packages/ClientRuntime/Sources/PrimitiveTypeExtensions/URLQueryItem+Extensions.swift
Change required for https://github.com/awslabs/aws-sdk-swift/pull/651
> fix: add explicit conformance for Equatable and Hashable on Header, Comparable on URLQueryItem

- Packages/ClientRuntime/Sources/PrimitiveTypeExtensions/String+Extensions.swift
- Packages/ClientRuntime/Tests/ClientRuntimeTests/PrimitiveTypeExtensionsTests/StringExtensionsTests.swift
Companion PR for https://github.com/awslabs/aws-sdk-swift/pull/660
> chore: add appendingPathComponent string extension

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/formurl/FormURLEncodeCustomizable.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/formurl/MemberShapeEncodeFormURLGenerator.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHttpEC2QueryProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/serde/ec2/OnlyFlattenedListEncodeFormURLGeneratorTests.kt
This PR provides a form url encoding customization option that allows for empty lists to be serialized.
Previously, empty lists would never be serialized.
https://github.com/awslabs/aws-sdk-swift/issues/665
> fix: Provide an encoding customization that allows empty lists to be serialized

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/CodegenVisitor.kt
https://github.com/awslabs/aws-sdk-swift/pull/709
This PR exposes the `model` property in `CodegenVisitor` to make the codegen behavior in tests more consistent with that in release.
> Exposes model property in CodegenVisitor

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/handlers/HttpBodyMiddleware.kt
- smithy-swift-codegen/src/test/kotlin/HttpBodyMiddlewareTests.kt
This PR properly encodes empty bodies. 
For JSON -> encode as "{}"
for XML -> encode as ""
[](https://github.com/awslabs/aws-sdk-swift/issues/580)
> fix: Properly encode empty bodies for json and xml

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/handlers/HttpBodyMiddleware.kt
- smithy-swift-codegen/src/test/kotlin/HttpBodyMiddlewareTests.kt
https://github.com/awslabs/aws-sdk-swift/issues/580
This PR removes the logic that encodes an empty string for an empty body in xml. 
Encoding an empty string, results in a "invalid list" error in CRT. (unknown if that is expected or not)
Regardless, doing nothing (or encoding nil) is preferable and more accurate as the expected payload should be empty.
> No-ops instead of encoding empty string when encoding an empty body in xml

- Package.swift
Use aws-crt-swift version 0.4.0, change version to locked rather than floating to next major
> chore: bump CRT to 0.4.0

- Packages/ClientRuntime/Sources/Networking/Http/Middlewares/SerializableBodyMiddleware.swift
- Packages/SmithyTestUtil/Sources/JSONComparator.swift
- Packages/SmithyTestUtil/Sources/RequestTestUtil/HttpRequestTestBase.swift
- Packages/SmithyTestUtil/Sources/XCTAssertions.swift
- Packages/SmithyTestUtil/Sources/XMLComparator.swift
- Packages/SmithyTestUtil/Tests/RequestTestUtilTests/HttpRequestTestBaseTests.swift
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestRequestGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/OperationInputBodyMiddleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/handlers/HttpBodyMiddleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/xml/MemberShapeEncodeXMLGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/model/AddOperationShapes.kt
- smithy-swift-codegen/src/test/kotlin/ContentMd5MiddlewareTests.kt
- smithy-swift-codegen/src/test/kotlin/HttpProtocolClientGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/HttpProtocolUnitTestRequestGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/IdempotencyTokenTraitTests.kt
- smithy-swift-codegen/src/test/kotlin/serde/xml/StructEncodeXMLGenerationTests.kt
- smithy-swift-codegen/src/test/kotlin/serde/xml/UnionEncodeXMLGenerationTests.kt
This PR fixes the following XML encoding and decoding issues 
- Incorrect root key when serializing XML
- Incorrect serialized float and double values when value is not a number or infinity
Additionally, this PR improves our serialization tests. 
https://github.com/awslabs/aws-sdk-swift/issues/711
The root key for XML is now the correct value. Previously, we didn't use the `xmlName` trait if one existed, nor did we account for the fact that our local swift models do not have the same name as their counterparts defined in the smithy model. This PR ensures that we now use the value defined by the `xmlName` trait (if one exists). it also sets the value of the `xmlName` trait to the shape's original name (as defined in the smithy model) if the shape doesn't define it's own explicit `xmlName`. …
> Fixes XML encoding issues

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/waiters/JMESPathVisitor.kt
Fixes rendering of JMESPath AND expressions, which render improperly because the debug description of the `JMESVariable`s being ANDed is being inserted into Swift code instead of the variable name.
I will write an acceptor functional test using AND in the `aws-sdk-swift` repo.
> fix: Use correct var name in AND expression

- Packages/ClientRuntime/Sources/Waiters/JMESUtils.swift
- Packages/ClientRuntime/Tests/WaiterTests/JMESUtilsTests.swift
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/waiters/JMESPathVisitor.kt
When building the SDK with waiters, it was discovered that JMES compare expressions with integers and `==`, and with doubles and `!=`, fail to compile due to ambiguity in resolving the operator.
- The Integer / `==` problem is resolved by requiring a Double comparator, then converting the Ints to Double before comparison.
- The Double / `!=` problem is resolved by using `!JMESUtils.compare(a, ==, b)` instead of `JMESUtils.compare(a, !=, b)` when inequality is to be tested.
Unit tests have been added to this PR to test compile-time resolution of various arguments to `JMESUtils.compare(_:_:_:)`.  Generated tests for number equality & inequality expressions are being added in a separate PR.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> fix: Correct Swift compile errors for comparison expressions

- design/waiters.md
Completes https://github.com/awslabs/aws-sdk-swift/issues/766
Adds the design doc for the Waiters feature as a Markdown doc, updated to reflect the final implementation.
> chore: Add waiters design doc to `design/` folder

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/json/MemberShapeDecodeGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/json/MemberShapeEncodeGenerator.kt
- smithy-swift-codegen/src/test/kotlin/StructDecodeGenerationTests.kt
- smithy-swift-codegen/src/test/kotlin/StructEncodeGenerationIsolatedTests.kt
- smithy-swift-codegen/src/test/kotlin/StructEncodeGenerationTests.kt
- smithy-swift-codegen/src/test/kotlin/UnionDecodeGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/UnionEncodeGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/serde/awsjson11/NestedListEncodeJSONGenerationTests.kt
Fixes https://github.com/awslabs/aws-sdk-swift/issues/747
With the introduction of the `AWSSecurityLake` service, an SDK compile error was encountered when compiling the generated `encode(to:)` method for a model containing this property:
```
enableAllDimensions: [Swift.String:[Swift.String:[Swift.String]]]? = nil,
```
After investigation it was discovered that the SDK was not generating correct code for nested maps & collections, so the code generation for encoding nested Smithy Maps & Lists was corrected.
Correcting that code exposed a compile error on code for serializing & deserializing `@sparse` collections (i.e. arrays where elements my be nil, or dictionaries where values may be nil).  Codegen was also corrected for `@sparse` data types.
New local protocol tests are being added in …
> fix: Fix encoding of nested maps when generating encoders

- Sources/ClientRuntime/Networking/Http/HttpBody.swift
- Tests/ClientRuntimeTests/NetworkingTests/HttpBodyTests.swift
This PR fixes S3 errors failing to parse by providing an accurate definition for `HttpBody.isEmpty`.
https://github.com/awslabs/aws-sdk-swift/issues/761
> fix: Adds `HttpBody.isEmpty` to help parse S3 404 errors properly

- Sources/ClientRuntime/Config/DefaultSDKRuntimeConfiguration.swift
- Sources/ClientRuntime/Config/SDKRuntimeConfiguration.swift
- Sources/ClientRuntime/Middleware/RetryerMiddleware.swift
- Sources/ClientRuntime/Networking/Http/HttpContext.swift
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ClientRuntimeTypes.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpBindingProtocolGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/RetryMiddleware.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareExecutionGenerator.kt
- smithy-swift-codegen/src/test/kotlin/ContentMd5MiddlewareTests.kt
- smithy-swift-codegen/src/test/kotlin/HttpProtocolClientGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/IdempotencyTokenTraitTests.kt
- smithy-swift-codegen/src/test/kotlin/RetryMiddlewareTests.kt
Partially accomplishes [#699](https://github.com/awslabs/aws-sdk-swift/issues/699)
Retry functionality is being moved from `aws-sdk-swift` to this project.  Retry configuration specific to AWS will continue to reside there.
The corresponding PR in `aws-sdk-swift`: https://github.com/awslabs/aws-sdk-swift/pull/806
Specific changes:
- Move retry middleware from SDK (runtime & codegen components) from `aws-sdk-swift` to here.  The retry middleware used to access region (an AWS-specific construct) directly to construct a "partition ID" (used for grouping requests for retry purposes); that dependency was broken by adding a parameter for partition ID.
- Partition ID for an operation is determined from a new, optional field on `SDKRuntimeConfiguration`.  When Partition ID is not set to an …
> feat: Move retry middleware from SDK

- Sources/ClientRuntime/Networking/ClientError.swift
- Tests/ClientRuntimeTests/ClientRuntimeTests/NetworkingTests/ClientErrorTests.swift
Fixes https://github.com/awslabs/aws-sdk-swift/issues/781
Under some circumstances, an error received from an operation will be embedded in a `ClientError.retryError()`.  When this happens, a waiter cannot detect the error's type because `ClientError` does not conform to `WaiterTypedError` and does not return the error type of the underlying error it contains.
This PR addresses the problem by adding `WaiterTypedError` conformance to `ClientError` and enabling it to return the error code from the Swift `Error` it contains.  Unit tests are added to `ClientError` as well.
I have tested this with AWS S3 and EC2 waiters, and found it corrects the issue linked above.
> fix: Add WaiterTypedError conformance to ClientError

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/PaginatorGenerator.kt
- smithy-swift-codegen/src/test/kotlin/PaginatorGeneratorTest.kt
Fixes https://github.com/awslabs/aws-sdk-swift/issues/727
Verified with
```
///.*
extension
```
There are no more comments that are supposed to be on method but placed on extension.
> fix: move paginator doc comments to methods

- Sources/ClientRuntime/Networking/Http/CRT/CRTClientEngine.swift
On iOS and watchOS, SDK fails to build.
> fix: change socketOptions to mutable to allow mutation on iOS and watchOS

- .github/workflows/continuous-integration.yml
Set the `AWS_SWIFT_SDK_USE_LOCAL_DEPS` env var so that the downstream SDK build uses locally installed dependencies.
> fix: Configure env var for downstream build so it uses local deps

- .github/workflows/lint.yml
Fixes https://github.com/awslabs/aws-sdk-swift/issues/677
The SwiftLint project now has containerized SwiftLint available for use:
https://github.com/realm/SwiftLint/pkgs/container/swiftlint
Use the latest stable Dockerized SwiftLint version (currently `0.50.3`) to lint this project.
No new dependencies were added to this change.
> chore: Use containerized swiftlint

- Sources/ClientRuntime/Networking/SdkError.swift
- Sources/ClientRuntime/Serialization/Encoder/XMLEncoder+Extensions.swift
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/providers/HttpQueryItemProvider.kt
Fixes two different Swift compile warnings thrown when building the AWS SDK.
- `SdkError` no longer conditionally casts `ClientError` to `WaiterTypedError` since `WaiterTypedError` always conforms.
- The `encode(_:)` function on `XMLEncoder` is changed from `open` to `public` to fix `Non-'@objc' instance method in extensions cannot be overridden; use 'public' instead`
After this change, the only compile warnings remaining on the SDK service clients are:
- Deprecated model properties
- The query items property is written as a literal `[]` when no items will be added to it (was going to fix this here, but it needs further investigation)
> fix: two Swift compile warnings

- Package.swift
- Sources/ClientRuntime/Networking/ClientError.swift
- Sources/ClientRuntime/Networking/Http/CRT/CRTClientEngine.swift
- Sources/ClientRuntime/Networking/Http/SdkHttpRequest.swift
- Sources/SmithyTestUtil/ResponseTestUtil/HttpResponseTestBase.swift
- Tests/ClientRuntimeTests/ClientRuntimeTests/NetworkingTests/ClientErrorTests.swift
Fixes https://github.com/awslabs/aws-sdk-swift/issues/835
Related https://github.com/awslabs/aws-sdk-swift/pull/862
We have new aws-crt-swift version available which has breaking changes.
- Pass bootstrap parameter
- HTTP Client in CRT now accepts updated callbacks which no longer has stream. Hence, updated the callback uses to reflect the changes.
- No functional changes
- Verified S3 list bucket and get object operation
- 
> chore: bump aws-crt-swift to 0.5.6

- .github/workflows/continuous-integration.yml
- Package.swift
https://github.com/awslabs/aws-sdk-swift/issues/867
This PR is a hot fix on smithy-swift 0.10.3.
- Update aws-crt-swift to 0.5.8 to pull in the fix for https://github.com/awslabs/aws-sdk-swift/issues/867
- When building, set the env var `AWS_SDK_SWIFT_USE_LOCAL_DEPS` so the downstream build uses this branch
> fix: Update aws-crt-swift to 0.5.8 to get fix for SDK #867

- Package.swift
Pulls in fix for https://github.com/awslabs/aws-sdk-swift/issues/867
Fixes an issue that prevents the SDK from building to an iOS device when building on a M series Mac.
> fix: Update aws-crt-swift to 0.6.1

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpBindingProtocolGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/LoggingMiddleware.kt
- smithy-swift-codegen/src/test/kotlin/ContentMd5MiddlewareTests.kt
- smithy-swift-codegen/src/test/kotlin/HttpProtocolClientGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/IdempotencyTokenTraitTests.kt
This PR moves the order of the middlewares so that the LoggingMiddleware comes after the DeserializeMiddleware which means logging will take place before deserializing. This allows logging of the response to take place regardless if decoding fails or not. 
This will greatly help debug issues such as decoding failures.
https://github.com/awslabs/aws-sdk-swift/issues/923
> fix: Logs responses regardless if decoding fails

- Sources/ClientRuntime/Networking/Streaming/DataStreamReader.swift
- Tests/ClientRuntimeTests/StreamingTests/DataStreamReaderTests.swift
This PR fixes an issue where subsequent reads from a DataStreamReader would return an unexpected value when the preceding read specified `rewind: true`. 
Passing in `rewind: true` when reading from a DataStreamReader should allow the next read to also read the same data. 
https://github.com/awslabs/aws-sdk-swift/issues/865
> fix: Reading from a `DataStreamReader` with `rewind: true` properly rewinds the stream allowing for subsequent reads.

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ImportDeclarations.kt
- smithy-swift-codegen/src/test/kotlin/ImportDeclarationsTest.kt
https://github.com/awslabs/aws-sdk-swift/issues/947
Allows code-generated Swift import statements to have multiple `@spi()` annotations so that multiple system programming interfaces may be used in the same Swift source file.  (Currently only `Internal` may be imported as a SPI.)
- Module imports now maintain a set of SPI names, instead of a single optional name.
- Add tests for proper import generation.
> feat: Allow multiple @_spi() imports in code generated Swift

- Sources/ClientRuntime/EventStream/DefaultMessageDecoderStream.swift
- Sources/ClientRuntime/EventStream/DefaultMessageEncoderStream.swift
- Sources/ClientRuntime/Networking/Http/CRT/CRTClientEngine.swift
- Sources/ClientRuntime/Networking/Http/CRT/CRTClientEngineConfig.swift
- Sources/ClientRuntime/Networking/Http/HttpContext.swift
- Sources/ClientRuntime/Networking/Http/ProtocolType.swift
- Sources/ClientRuntime/Networking/Http/SdkHttpClient.swift
- Tests/ClientRuntimeTests/NetworkingTests/CRTClientEngineIntegrationTests.swift
This PR forces http2 for bidirectional event streams and updates the CRT http engine, to use a http2 specific connection manager when forcing http2. 
https://github.com/awslabs/aws-sdk-swift/issues/870
> feat: Forces http2 for bidirectional event streams

- Sources/ClientRuntime/Networking/Endpoint.swift
- Tests/ClientRuntimeTests/NetworkingTests/EndpointTests.swift
Fixes https://github.com/awslabs/aws-sdk-swift/issues/945
It was discovered while investigating the issue linked above that the Linux implementation of Foundation's `URLQueryItem` does not implement the `Hashable` protocol correctly.  This ticket is filed in the `swift-corelibs-foundation` project to identify & track the issue:
https://github.com/apple/swift-corelibs-foundation/issues/4737
In the interim, this PR provides an implementation of `Hashable` for the `Endpoint` type that will allow `Endpoint` to meet the contract for hashability, by hashing query items with a private type that will hash correctly on all platforms.
> fix: Provide Endpoint hasher to work around URLQueryItem bug

- Sources/ClientRuntime/EventStream/DefaultMessageDecoderStream.swift
- Sources/ClientRuntime/Networking/Streaming/Stream.swift
This pr adjusts while-loop tick rate to 1ms which reduces the CPU usage of event streams from 100%+ down to ~9%
[](https://github.com/awslabs/aws-sdk-swift/issues/974)
> fix: Prevents event-streams from hogging CPU

- .github/workflows/continuous-integration.yml
- Tests/ClientRuntimeTests/ClientRuntimeTests/MiddlewareTests/OperationStackTests.swift
- Tests/ClientRuntimeTests/ClientRuntimeTests/SerializationTests/SerializationUtilsTests/DataObjectSerializationTests.swift
- Tests/ClientRuntimeTests/SerializationTests/SerializationUtilsTests/TimestampSerdeUtilsTests.swift
- Tests/SmithyTestUtilTests/RequestTestUtilTests/HttpRequestTestBaseTests.swift
https://github.com/awslabs/aws-sdk-swift/issues/1005
Unit tests for `smithy-swift` are crashing on Linux + Swift 5.5 & 5.6 and two tests are not passing on any Linux + Swift.
To diagnose:
- A matrix of Linux + Swift combinations was created and CI is run on each, in addition to the existing CI which runs on Mac.  These will be marked as "Required" to pass once this PR merges.
To fix:
- Two tests used the `wait(for:timeout:)` method in asynchronous context.  This method is incompatible with async because it blocks the main thread and can cause deadlock.  The tests did not actually require waiting on expectations since the code under test executes in a deterministic order, so the use of expectations & `wait(for:timeout:)` was removed from each test.
- Two tests that do not pass on Linux …
> fix: Fix tests & add CI coverage for unit tests on Linux

- Sources/ClientRuntime/Retries/ExponentialBackoffStrategy.swift
- Sources/ClientRuntime/Retries/RetryStrategyOptions.swift
Provide a public initializer for `RetryStrategyOptions` so that the AWS SDK may customize retry parameters.
> feat: Make RetryStrategyOptions initializer public

- Tests/ClientRuntimeTests/ClientRuntimeTests/SerializationTests/SerializationUtilsTests/DataObjectSerializationTests.swift
- Tests/ClientRuntimeTests/SerializationTests/SerializationUtilsTests/TimestampSerdeUtilsTests.swift
This PR addresses 2 unit tests that were failing on linux but not on mac os.
https://github.com/awslabs/aws-sdk-swift/issues/1006
**Addressing Test Failure #1**: TimestampSerdeUtilsTests.test_timestampEncodable_encodesDateAsExpectedForEachFormat failed as in linux 673351930.12300003 was rounded to 673351930.123. Since this difference is negligble I've converted the string comparison to a Double comparison with accuracy of 0.001 to allow flexibility across platforms. There are open issues in swift-corelibs-foundation which may be relevant ([#3658](https://github.com/apple/swift-corelibs-foundation/issues/3658), [#4255](https://github.com/apple/swift-corelibs-foundation/issues/4255)).
**Addressing Test Failure #2**: DataObjectSerializationTests.testDecodingInvalidBase64EncodedDataObject …
> fix: Re-enable two unit tests on Linux

- Sources/ClientRuntime/Waiters/WaiterOutcome.swift
This PR addresses the inability to mock WaiterOutcome by providing a public initializer.
https://github.com/awslabs/aws-sdk-swift/issues/1068
Add a public initializer to WaiterOutcome with required parameters attempts and result. This will allow users to create an instance of WaiterOutcome in scripts that depend on smithy-swift.
I was able to reproduce the issue in #1068 using the code provided. With this change I am able to successfully build and the error "'WaiterOutcome' initializer is inaccessible due to 'internal' protection level" no longer occurs.
```
import XCTest
import AWSS3
import class Foundation.Bundle
@testable import ClientRuntime
// define a protocol with our method
protocol WaitUntilBucketExistsDefaults {
func waitUntilBucketExists(options: WaiterOptions, input: …
```
> feat: add public initializer to WaiterOutcome

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/xml/MemberShapeDecodeXMLGenerator.kt
- smithy-swift-codegen/src/test/kotlin/serde/xml/MemberShapeDecodeXMLGeneratorTests.kt
This PR addresses the deserialization error where a default value is not correctly assigned to fields when they're missing from server response.
https://github.com/awslabs/aws-sdk-swift/issues/602
Issue #602 is resolved by properly assigning the default value (`false` in this case) to [deleteMarker](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeletedObject.html#:~:text=Contents-,DeleteMarker,-Indicates%20whether%20the) property (a boolean member) of [DeletedObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeletedObject.html) when it is not found in S3 server response due to the responding bucket not being versioned.
With this change, when the deserializer tries to decode server response to [S3:deleteObjects](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjec …
> fix: Add default value handling for a scalar member of server response struct

- Package.swift
Requires the latest stable version of `aws-crt-swift`.
> chore: Require aws-crt-swift 0.13.0

- README.md
Adds trivial whitespace change to README.  Needed to prevent release from failing since there have been no changes to `smithy-swift` since the last Swift SDK release.  See https://github.com/awslabs/aws-sdk-swift/issues/1060
> chore: Add whitespace to README

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpBindingProtocolGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/json/MemberShapeDecodeGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/json/StructDecodeGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/json/UnionDecodeGenerator.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHttpAWSJson11ProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHttpEC2QueryProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHttpRestJsonProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHttpRestXMLProtocolGenerator.kt
https://github.com/awslabs/aws-sdk-swift/issues/1100
Fixes serializers / deserializers for errors that are embedded in event streams, by accounting for the custom error properties being namespaced under `properties`.
> fix: Correct serde for errors in event streams

- Sources/ClientRuntime/Util/SwiftVersion.swift
https://github.com/awslabs/aws-sdk-swift/issues/1135
Swift 5.9 was just released with Xcode 15.  The Swift core team has indicated that the release of Swift 6 is not imminent, so further Swift 5 minor releases are expected.
This PR extends the Swift metadata generation to handle Swift 5 minor versions up to Swift 5.19.
> chore: Support Swift 5.x versions past 5.9 in metadata

- Sources/SmithyTestUtil/RequestTestUtil/HttpRequestTestBase.swift
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/formurl/MemberShapeEncodeFormURLGenerator.kt
https://github.com/awslabs/aws-sdk-swift/issues/1121
When generating the serializer for `x-www-url-encoded` forms, the "lowerCamelCase" form of the member name is used when serializing timestamps.  This can cause errors at the server because the field name does not have the correct capitalization.
- This change uses the original member name to construct the form, so that URL-encoded forms containing timestamps may be read.
- Protocol tests for proper request serialization are in the corresponding `aws-sdk-swift` PR: https://github.com/awslabs/aws-sdk-swift/pull/1137
Also: Improve the messaging when a protocol test fails with non-matching query string parameters.
> fix: Use original member name for serialization of URL-encoded forms

- Sources/ClientRuntime/Networking/Http/SdkHttpRequest.swift
- Tests/ClientRuntimeTests/NetworkingTests/HttpRequestTests.swift
Provide the ability to add additional headers to an existing request of type SdkHttpRequest.
[#1130](https://github.com/awslabs/aws-sdk-swift/issues/1130)
#583 
Cause: `headers` is already a mutable property but it is computed without any stored values. This means that a customer who attempts to modify headers will either have no effect (because computed properties are read-only) or because it points to an instance of `endpoint.headers` whose headers are immutable. 
Solution: Add `additionalHeaders` stored property which is mutable and provide add/removal methods.
Risk: Computed properties ensure that the request is never modified in-transit. In order to reduce any risk associated I have chosen to add a new property that is mutable, stores values, and provided my own setters rather than …
> feat: add stored property for adding additional headers in SdkHttpRequest

- Sources/ClientRuntime/Config/DefaultSDKRuntimeConfiguration.swift
- Sources/ClientRuntime/Networking/Http/CRT/CRTClientEngine.swift
- Sources/ClientRuntime/Networking/Http/CRT/CRTClientEngineConfig.swift
Expose connectTimeoutMs so that it is configurable on the client.
[#1065](https://github.com/awslabs/aws-sdk-swift/issues/1065)
[#1152](https://github.com/awslabs/aws-sdk-swift/pull/1152)
Ex. Usage
```
// I set timeout to 15_000 as an example but this could be any UInt32 number
let httpClientConfiguration = HttpClientConfiguration()
let crtEngine = CRTClientEngine(CRTClientEngineConfig(connectTimeoutMs: 15_000))
let httpClient = SdkHttpClient(engine: crtEngine, config: httpClientConfiguration)
```
> feat: make connectTimeoutMs configurable

- Sources/ClientRuntime/Auth/HTTPAuthAPI/Signer.swift
- Sources/ClientRuntime/Identity/IdentityAPI/Identity.swift
- Sources/ClientRuntime/Networking/Http/HttpContext.swift
Milestone ticket: https://github.com/awslabs/aws-sdk-swift/issues/1143
Corresponding PR in `aws-sdk-swift`: https://github.com/awslabs/aws-sdk-swift/pull/1167
Adds protocol that every signer must conform to. Required to adopt SRA identity & auth signing flow that makes use of dynamic dispatching based on interface.
`HttpContext` is refactored to have methods in alphabetical order & to have a single place that holds definitions of `AttributeKey`s.
> chore: Add signer protocol.

- Package.swift
- Sources/ClientRuntime/Retries/DefaultRetryStrategy/RetryQuota.swift
- Sources/ClientRuntime/Util/SwiftVersion.swift
https://github.com/awslabs/aws-sdk-swift/issues/1010
- Sets minimum required Swift version to 5.7 or greater
- Fixes deprecation warnings for Swift code
> chore: Require Swift 5.7, fix deprecation warnings

- Sources/ClientRuntime/Util/PlatformOperatingSystem.swift
Add limited support in smithy-swift for visionOS. Currently, we throw an error if a user tries to compile for visionOS. While we may not provide full support for it or put effort into testing related features, we should allow users to experiment with it and support the SDK compiling.
Add visionOS as a supported platform.
> feat: add limited support in smithy-swift for visionOS

- Sources/ClientRuntime/Networking/Http/Middlewares/ContentLengthMiddleware.swift
- Sources/ClientRuntime/Util/PlatformOperatingSystem.swift
- Tests/ClientRuntimeTests/NetworkingTests/ContentLengthMiddlewareTests.swift
Event streams should not be subject to logic that applies only to data streams
https://github.com/awslabs/aws-sdk-swift/issues/1177
- Add back default behavior of adding `Transfer-Encoding: Chunked` header on any event streams where length cannot be calculated
- Have `ContentLengthMiddleware()` default behavior used by non-blob streams set requiresLength and unsignedPayload to nil since these traits are only relevant for determining failure condition on blob stream
- Add test for this scenario
- Confirmed that structure of AWS Transcribe (failing integration test) would code-generate `ContentLengthMiddleware()`
> fix: content-length middleware should not error on event streams

- Sources/ClientRuntime/Idempotency/IdempotencyTokenMiddleware.swift
- Tests/ClientRuntimeTests/Idempotency/IdempotencyTokenMiddlewareTests.swift
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ClientRuntimeTypes.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/IdempotencyTokenMiddleware.kt
- smithy-swift-codegen/src/test/kotlin/ContentMd5MiddlewareTests.kt
- smithy-swift-codegen/src/test/kotlin/HttpProtocolClientGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/IdempotencyTokenTraitTests.kt
https://github.com/awslabs/aws-sdk-swift/issues/1202
Changes the idempotency token middleware from an anonymous closure that is rendered inline at every point of use to a reusable Swift type that is placed under unit test.
The reusable middleware uses Swift key paths to specify the idempotency token member on the input structure; the input structure type and the key path are passed as initialization parameters to the reusable middleware.
We currently have ~710 operations that use idempotency tokens throughout the SDK, and this change reduces generated SDK size by about 5000 lines by not duplicating the idempotency token code at every point of use.
> chore: Convert idempotency token middleware from closure to reusable type

- Package.swift
https://github.com/aws-amplify/amplify-swift/issues/3324
Update to aws-crt-swift 0.17.0: https://github.com/awslabs/aws-crt-swift/releases/tag/0.17.0
(This PR will be used to create a patch release 0.30.1 of smithy-swift)
> fix: Require aws-crt-swift 0.17.0

- Sources/ClientRuntime/Networking/Endpoint.swift
- Tests/ClientRuntimeTests/NetworkingTests/HttpRequestTests.swift
URL extension was set to optional to account for nil properties, but nil was never returned. As a result there was a TODO in the test wondering when endpoint.url should be nil.
[#710](https://github.com/awslabs/aws-sdk-swift/issues/710)
- Update code logic to set url to nil if host or scheme is nil (invalid URL)
- Update test to check for nil URL
- Remove TODO
> fix: Endpoint url should be nil if host or scheme is missing

- Sources/ClientRuntime/Logging/SDKLoggingSystem.swift
Make it possible to set specific log configuration to some items and then a default one for non-set ones.
Adding default value as parameter to initialize method
Edit: Just noticed the commit should have a special [format](https://github.com/smithy-lang/smithy-swift/blob/main/CONTRIBUTING.md) sorry.. 
> add default log level to initialize method

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ServiceGenerator.kt
- smithy-swift-codegen/src/test/kotlin/ContentMd5MiddlewareTests.kt
- smithy-swift-codegen/src/test/kotlin/HttpProtocolClientGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/IdempotencyTokenTraitTests.kt
https://github.com/awslabs/aws-sdk-swift/issues/730
Adds a header at the top of the documentation comment block for an operation function.
This improves the layout of generated Xcode / docc documentation.
Also: cleaned up the format of affected codegen tests.
> fix: Add a header to operation doc comments

- Sources/ClientRuntime/Pagination/PaginatorSequence.swift
S3's ListParts had a nullability change for `isTruncated`
[#1021](https://github.com/awslabs/aws-sdk-swift/issues/1021)
Change type of `isTruncated` and `isTruncatedKey` to accept an optional bool and default to false
> fix: allow isTruncated to be optional bool

- Package.swift
Conditionally adding libxml2 on the Linux platform caused an unintended warning on Macs when resolving packages.
This PR adds libxml2 only on Linux (using conditional compilation) so that warnings on Mac are avoided.
> fix: Fix Package.swift warning on Mac

- Sources/ClientRuntime/Networking/Streaming/ByteStream.swift
#634 
Add back helper method from 0.36.0 to create a Bytestream .stream from FileStream(filehandle)
Usage: `let fileByteStream = ByteStream.from(fileHandle: fileHandle)`
> fix: add back from method with fileHandle

- Sources/ClientRuntime/Logging/SDKLoggingSystem.swift
https://github.com/awslabs/aws-sdk-swift/issues/903
Calling `bootstrap` method of `swift-log`'s `LoggingSystem` more than once per program execution results in unexpected behavior ([swift-log spec](https://github.com/apple/swift-log/blob/e97a6fcb1ab07462881ac165fdbb37f067e205d5/Sources/Logging/Logging.swift#L672-L674)), most likely a crash.
To avoid this crash, no-op behavior is added to `SDKLoggingSystem` which wraps `LoggingSystem`. Whether the `initialize` methods have been already called or not is internally recorded to `isInitialized` variable. If yes, methods return with no-op done.
To make it thread-safe, `SDKLoggingSystem` is made an actor, and methods made async. This change is a breaking change. 
- [] Bug fix (non-breaking change which fixes an issue)
By submitting this pull …
> fix!: Add no-op behavior for initialize methods of logging system.

- Sources/ClientRuntime/Networking/HashFunction.swift
- Tests/ClientRuntimeTests/NetworkingTests/HashFunctionTests.swift
Create a wrapper class to utilize hash/checksum functions. We will read desired checksum from an enum and want to go from string -> hash function -> computed value -> hexadecimal string easily based on whatever input algorithm is chosen.
[#1287](https://github.com/awslabs/aws-sdk-swift/issues/1287)
- Add a HashFunction class that wraps hash/checksum implementations in CRT swift
- Add ability to go from string -> hash function and use .computeHash() to get the returned value which is of type `HashResult` and be either a .data(Data) or a .integer(UInt32)
- Add ability to go from Data -> hexadecimal string using %02 or UInt32 -> hexadecimal string using %08
- Unit tests for class
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> feat: add wrapper for checksums + unit tests

- Sources/ClientRuntime/Auth/HTTPAuth/DefaultIdentityResolverConfiguration.swift
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/AuthSchemeResolverGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ClientRuntimeTypes.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpBindingProtocolGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolServiceClient.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/middlewares/SignerMiddleware.kt
https://github.com/awslabs/aws-sdk-swift/issues/1148
* Rename signer middleware kotlin name in the codegen backend to be consistent with runtime swift name
* Correct the default identity resolver configuration’s only member variable to be a list of identity resolvers rather than a single identity resolver
* Use newly added sigv4a trait to add sigv4a auth scheme to service client config's list of supported auth schemes during codegen
> feat: tie up some loose ends

- Sources/ClientRuntime/Config/DefaultSDKRuntimeConfiguration.swift
https://github.com/awslabs/aws-sdk-swift/issues/817
Uses the Foundation HTTP client by default on the Mac platform.
> feat: Use the Foundation HTTP client by default on Mac

- Sources/ClientRuntime/PrimitiveTypeExtensions/URLQueryItem+Extensions.swift
in aws-sdk-swift: https://github.com/awslabs/aws-sdk-swift/issues/1229
in smithy-swift: https://github.com/smithy-lang/smithy-swift/issues/561
Renames typealias of ClientRuntime.URLQueryItem.
> chore: change MyURLQueryItem to SDKURLQueryItem

- Package.swift
https://github.com/awslabs/aws-sdk-swift/issues/1334
Updates aws-crt-swift to 0.26.0.  This version of aws-crt-swift removes the swift-collections dependency to avoid a build failure.
> chore: Update aws-crt-swift to 0.26.0

- .github/workflows/continuous-integration.yml
https://github.com/awslabs/aws-sdk-swift/issues/1339
Moves Apple platform CI from Intel Mac to M1 Mac.
Also updates several GH Action versions, and oldest/newest Xcode versions.
> chore: Move Apple-platform CI to Apple Silicon

- Sources/ClientRuntime/Networking/Http/CRT/CRTClientEngine.swift
[Here](https://github.com/awslabs/aws-crt-swift/blob/13e5479c41e55e0fe0c5ce10252af46df1a1d97a/Source/AwsCommonRuntimeKit/http/HTTPClientConnectionOptions.swift#L22) in aws-crt-swift, the documentation states that tlsOptions must be null for HTTP connections.
In fact, CRT HTTP client fails to connect to servers if the connection is HTTP currently.
Added a small change that checks protocol type and assigns nil to it if it is HTTP instead of HTTPS.
> fix: Make tlsOptions nil for CRT HTTP client if protocol type is HTTP

- Sources/ClientRuntime/Networking/Endpoint.swift
- Sources/ClientRuntime/Networking/Http/ProtocolType.swift
- Sources/ClientRuntime/Networking/Http/URLSession/URLSessionHTTPClient.swift
https://github.com/awslabs/aws-sdk-swift/issues/1348
- Set the port number when preparing a URLSession HTTP request.  The port number was ignored before.  (When the default port is explicitly specified, omit it for clarity.)
- On `Endpoint`, when no port is supplied, use the default port for the chosen URL scheme (http/https) as the default, instead of always choosing 443 (the default https port.)
NOTE: Use of non-TLS http:// connections with the URLSession HTTP client is controlled by the ATS (App Transport Security) feature when run on Apple platforms.
- ATS allows connections to localhost by default (Verified this behavior on the desktop with a local server.)
- ATS must be disabled to reach a http:// server in any other location.
By submitting this pull request, I confirm that my …
> fix: Set ports and scheme correctly for non-TLS HTTP connections

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ServiceNamespaceIntegration.kt
https://github.com/awslabs/aws-sdk-swift/issues/1356
Change the directory for the model namespace file from `Models/` to `models/` which matches other models and prevents orphaned files when code-generating on Linux systems.
> fix: Use 'models' with lowercase 'm' for directory name

- Sources/ClientRuntime/Client/Client.swift
- Sources/ClientRuntime/Client/ClientBuilder.swift
- Sources/ClientRuntime/Config/ClientConfiguration.swift
- Sources/ClientRuntime/Config/DefaultClientConfiguration.swift
- Sources/ClientRuntime/Config/DefaultHttpClientConfiguration.swift
- Sources/ClientRuntime/Plugins/DefaultClientPlugin.swift
- Sources/ClientRuntime/Plugins/Plugin.swift
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ClientRuntimeTypes.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/DefaultClientConfigurationIntegration.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/Dependency.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/SwiftDependency.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/config/ClientConfiguration.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/config/ConfigProperty.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/config/DefaultClientConfiguration.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/config/DefaultHttpClientConfiguration.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/config/DefaultProvider.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/ClientProperty.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolServiceClient.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/Plugin.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/ServiceConfig.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/SwiftIntegration.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/model/SymbolBuilder.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/plugins/DefaultClientPlugin.kt
- smithy-swift-codegen/src/main/resources/META-INF/services/software.amazon.smithy.swift.codegen.integration.SwiftIntegration
- smithy-swift-codegen/src/test/kotlin/HttpProtocolClientGeneratorTests.kt
Add runtime plugins functionality to smithy swift.
A runtime plugin defines instructions for how an SDK client is configured. For example, a plugin can be initialized and passed to the client as follows:
```
let s3Client = S3Client.builder()
.withPlugin(new VeyronPlugin())
.build();
```
* `ClientConfiguration` is an interface that includes settings that can be modified on a service client. Because services have different configuration, each service has a code-generated ClientConfiguration implementation. (`DefaultClientConfiguration` and `DefaultHttpClientConfiguration` specify default client config properties and will always be present.)
* `ConfigProperty` specifies the name, type and default value of the client configuration property.
* A `Plugin` is an object allowing users to modifies …
> feat: add runtime plugins

- Sources/ClientRuntime/Config/DefaultHttpClientConfiguration.swift
- Sources/ClientRuntime/Plugins/DefaultClientPlugin.swift
- Sources/ClientRuntime/Plugins/HttpClientPlugin.swift
- Sources/ClientRuntime/Plugins/RetryPlugin.swift
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ClientRuntimeTypes.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/config/ClientConfiguration.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/config/ConfigProperty.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/config/DefaultClientConfiguration.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/config/DefaultHttpClientConfiguration.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolServiceClient.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/Plugin.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/SwiftIntegration.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/model/SymbolBuilder.kt
- smithy-swift-codegen/src/test/kotlin/HttpProtocolClientGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/ServiceRenamesTests.kt
- smithy-swift-codegen/src/test/kotlin/TestUtils.kt
* Add retry and http client plugins
> feat: add retry and http client plugins

- Sources/ClientRuntime/Auth/HTTPAuthAPI/SelectedAuthScheme.swift
- Sources/ClientRuntime/Plugins/AuthSchemePlugin.swift
- Adds convenience method to `SelectedAuthScheme` to be used to overwrite a signing property value.
> fix: Add overwrite behavior for endpoints 2.0 for signing properties

- Sources/ClientRuntime/Networking/Http/URLSession/FoundationStreamBridge.swift
https://github.com/awslabs/aws-sdk-swift/issues/1399
It has been observed that when using the URLSession-based HTTP client, HTTP requests occasionally time out because the request does not stream its data to the server as expected.  The cause is that the run loop for stream event handling sometimes does not start.  Per Apple's docs:
```
If no input sources or timers are attached to the run loop, this method exits immediately; otherwise, it runs the receiver in the NSDefaultRunLoopMode by repeatedly invoking `run(mode:before:)`.
```
(https://developer.apple.com/documentation/foundation/runloop)
No input sources or timers are added to the stream event handling run loop's thread before it is started.  This creates a race condition between two events:
a) scheduling an event on the run loop in …
> fix: Race condition on URLSession HTTP client request body

- Sources/ClientRuntime/Config/DefaultClientConfiguration.swift
- Sources/ClientRuntime/Config/DefaultSDKRuntimeConfiguration.swift
- Sources/ClientRuntime/Plugins/TelemetryPlugin.swift
- Sources/ClientRuntime/Telemetry/DefaultTelemetry.swift
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ClientRuntimeTypes.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/config/DefaultClientConfiguration.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/ExtractTelemetryLoggerConfig.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolServiceClient.kt
- smithy-swift-codegen/src/main/resources/META-INF/services/software.amazon.smithy.swift.codegen.integration.SwiftIntegration
- smithy-swift-codegen/src/test/kotlin/HttpProtocolClientGeneratorTests.kt
awslabs/aws-sdk-swift#696
**Note: dependent on DirectedCodegen implemented in #681 and awslabs/aws-sdk-swift#1405**
**Note: coupled with awslabs/aws-sdk-swift#1426**
Adds client observability configuration codegen. Notably, `config.logger` is replaced with
`config.telemetryProvider`, which provides a default `loggerProvider`.
Changes:
- Breaking change: replace config `logger` with `telemetryProvider`
- Breaking change: codegen client configuration `telemetryProvider`
- make top-level default telemetry impls public
- add telemetry runtime plugin
- Breaking change included
> feat!: add client observability configuration codegen

- smithy-swift-codegen/build.gradle.kts
Add the Smithy smoke-test APIs to the project so that smoke test traits do not cause an unhandled error during codegen.
> fix: Add Smithy smoke test APIs to project

- .github/workflows/continuous-integration.yml
Use Swift 5.10 & Xcode 15.3 as latest on CI.  This matches the Swift, Xcode, and sim versions in use on aws-sdk-swift.
> chore: Use Swift 5.10 & Xcode 15.3 as latest on CI

- Sources/ClientRuntime/Interceptor/AnyInterceptor.swift
- Sources/ClientRuntime/Interceptor/DefaultInterceptorContext.swift
- Sources/ClientRuntime/Interceptor/HttpInterceptor.swift
- Sources/ClientRuntime/Interceptor/Interceptor.swift
- Sources/ClientRuntime/Interceptor/InterceptorContext.swift
- Sources/ClientRuntime/Middleware/Attribute.swift
- Sources/ClientRuntime/Networking/Http/HttpContext.swift
- Tests/ClientRuntimeTests/InterceptorTests/InterceptorTests.swift
Add interceptors interfaces to client libraries.
Interceptors defines hooks that can be used to inject functionality into different phases of the operation execution pipeline.
- Adds the `Interceptor` protocol, which has methods defining the hooks into the operation execution pipeline. Protocol implementations can specify concrete types for the transport request/response types (i.e. `SdkHttpRequest`/`HttpResponse`), as well as a type that provides `Attributes` through the new `HasAttributes` protocol. This allows 'less specific' interceptors that don't care about the transport request/response types, or the available attributes, to be used with more specific interceptors. See an example in [InterceptorTests](Tests/ClientRuntimeTests/InterceptorTests/InterceptorTests.swift)
- Adds …
> feat: add interceptors interfaces

- Sources/ClientRuntime/Networking/Http/URLSession/FoundationStreamBridge.swift
- Sources/ClientRuntime/Networking/Http/URLSession/URLSessionHTTPClient.swift
- Tests/ClientRuntimeTests/NetworkingTests/URLSession/FoundationStreamBridgeTests.swift
https://github.com/awslabs/aws-sdk-swift/issues/1457
https://github.com/awslabs/aws-sdk-swift/issues/1467
- `FoundationStreamBridge` (and its tests) copied in from main branch to apply latest fixes.
- `URLSessionHTTPClient` updated to supply logger param to `FoundationStreamBridge`.
This PR merges to RC branch `jbe/0_41_1_rc`.  0.41.1 will be used in a hotfix to be released by amplify-swift.
> fix: FoundationStreamBridge fixes from main branch

- Sources/ClientRuntime/Networking/Http/URLSession/FoundationStreamBridge.swift
- Sources/ClientRuntime/Networking/Http/URLSession/URLSessionHTTPClient.swift
https://github.com/awslabs/aws-sdk-swift/issues/1457
- Code for managing HTTP connection continuations has been pulled into the Connection class to ensure continuations are managed properly
- Code paths through delegate methods have been audited to ensure that continuations are always resumed and streams are always closed on the completion of a connection
- Custom `deinit` has been added to connections that ensure their continuation/output stream are resumed/closed on dealloc
- One `fatalError()` was converted into a throwing error
> fix: URLSessionHTTPClient defensive fixes

- Sources/ClientRuntime/Networking/Http/URLSession/FoundationStreamBridge.swift
- Sources/ClientRuntime/Networking/Http/URLSession/URLSessionHTTPClient.swift
- Tests/ClientRuntimeTests/NetworkingTests/URLSession/FoundationStreamBridgeTests.swift
https://github.com/awslabs/aws-sdk-swift/issues/1457
- It was discovered that in certain circumstances, the `FoundationStreamBridge` can close while there is still data in the buffer left to stream.  This potential bug was corrected by ensuring that both the buffer is empty AND the readable stream is closed before closing the output stream.  (Before, we closed the output stream when the readable stream closed, without checking if there was data left to be streamed in the buffer.)
- If there is unwritten data in the buffer and the Foundation `OutputStream` has room to receive, the remaining buffer data is written prior to reading the `ReadableStream` for more.  This might increase the number of writes needed, but will ensure that available data is transferred to the Foundation …
> fix: Ensure all data is written before closing FoundationStreamBridge

- .github/workflows/codegen.yml
- build.gradle.kts
- gradle.properties
- smithy-swift-codegen-test-utils/build.gradle.kts
- smithy-swift-codegen/build.gradle.kts
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestResponseGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/readwrite/WritingClosureUtils.kt
There were a lot of noisy logs from Gradle / Kotlin, e.g.
```log
java.rmi.ServerError: Error occurred in server thread; nested exception is: 
Could not connect to kotlin daemon. Using fallback strategy.
java.lang.AssertionError: symbolic reference class is not accessible: class sun.nio.ch.FileChannelImpl, from class org.jetbrains.kotlin.com.intellij.util.io.FileChannelUtil (unnamed module @46805db7)
...
```
This PR should fix all of the noise (at least locally).
See related links:
- https://youtrack.jetbrains.com/issue/KT-47152/Incremental-Compilation-with-Kotlin-compile-daemon-and-JDK-17-fails-with-IllegalAccessException
- https://kotlinlang.org/docs/whatsnew18.html#updated-jvm-compilation-target
- https://stackoverflow.com/questions/77607619/android-studio-kotlin-inconsistent-jvm-target- …
> feat: bump kotlin version to 1.9.24

- Sources/ClientRuntime/Networking/Http/CRT/TLSConfiguration.swift
- Sources/ClientRuntime/Networking/Http/HttpClientConfiguration.swift
- Sources/ClientRuntime/Networking/Http/URLSession/FoundationStreamBridge.swift
- Sources/ClientRuntime/Networking/Http/URLSession/URLSessionConfiguration+HTTPClientConfiguration.swift
- Sources/ClientRuntime/Networking/Http/URLSession/URLSessionHTTPClient.swift
- Sources/ClientRuntime/Networking/Http/URLSession/URLSessionTLSOptions.swift
- Sources/ClientRuntime/Networking/Http/URLSession/URLSessionTLSResolverUtils.swift
- Tests/ClientRuntimeTests/NetworkingTests/URLSession/FoundationStreamBridgeTests.swift
https://github.com/awslabs/aws-sdk-swift/issues/1457
_NOTE: This PR merges to hotfix branch `rc/0.41.2`_
Moves in `URLSessionHTTPClient` changes from latest `main` branch to backport bugfixes to smithy-swift 0.41.
> fix: Bring in latest URLSessionHTTPClient from main branch

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/readwrite/WritingClosureUtils.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/struct/StructEncodeGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/union/UnionDecodeGenerator.kt
Some model files are being generated without the necessary imports.  This hasn't affected AWS services because models are combined into one file per service along with consolidating all the imports, but could cause a build failure on builds where models aren't merged to one file like test SDK or protocol tests.
> chore: Add imports to model files where needed

- .github/workflows/codegen.yml
- Sources/WeatherSDK/models/Baz+ReadWrite.swift
- Sources/WeatherSDK/models/Foo+ReadWrite.swift
- Sources/WeatherSDK/models/OtherStructure+ReadWrite.swift
- Sources/WeatherSDK/models/Precipitation+ReadWrite.swift
The Weather SDK codegen is out of sync, and there is no mechanism to check it.
Add codegen CI generated code check.
> chore: add codegen CI generated code check

- smithy-swift-codegen-test-utils/src/main/kotlin/software/amazon/smithy/swift/codegen/test/utils/TestProtocolGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HTTPBindingProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHTTPAWSJson11ProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHTTPEC2QueryProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHTTPRestJsonProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHTTPRestXMLProtocolGenerator.kt
`renderStructEncode()` and `renderStructDecode()` methods are moved into `HTTPBindingProtocolGenerator` and made private since all protocols now use the same implementation of these methods.
All of the overrides of these two methods are removed.
> chore: Move struct encode/decode to HTTPBindingProtocolGenerator

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/events/MessageMarshallableGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/events/MessageUnmarshallableGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HTTPBindingProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/EventStreamTests.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHTTPAWSJson11ProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHTTPEC2QueryProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHTTPRestJsonProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHTTPRestXMLProtocolGenerator.kt
- smithy-swift-codegen/src/test/resources/eventstream.smithy
- Move `MessageMarshallableGenerator` and `MessageUnmarshallableGenerator` from `aws-sdk-swift` to `smithy-swift` to support event streaming in non-AWS SDKs.
- Move message marshal/unmarshal support in `AWSHTTPBindingProtocolGenerator` up to smithy-swift superclass `HTTPBindingProtocolGenerator`.
- Moved event stream codegen tests from `aws-sdk-swift` to `smithy-swift`.
> chore: Move event marshal/unmarshal code to smithy-swift

- .github/workflows/continuous-integration.yml
- Use Xcode 15.4 as "latest" Xcode, along with latest iOS & tvOS sims.
- Use `xcbeautify` for processing `xcodebuild` logs instead of `xcpretty`.  (`xcpretty` is now an abandoned project, and Github recently started pre-installing the more up-to-date `xcbeautify` on its Mac runners.)
> chore: On CI, use Xcode 15.4 as latest instead of 15.3

- Sources/ClientRuntime/Config/DefaultSDKRuntimeConfiguration.swift
- Sources/ClientRuntime/Networking/Http/HttpResponse.swift
https://github.com/awslabs/aws-sdk-swift/issues/1324
https://github.com/aws-amplify/amplify-swift/issues/3708
Addresses SIM ticket `/V1219649867`.
A customer raised a SIM ticket with the following screenshot of data race warning on IDE:
To address this data race warning, use serial queue and hidden property `_statusCode` to make getter & setter thread-safe. Observed that the thread sanitization warning goes away when running CRT HTTP client with this change.
> fix: Make HttpResponse.statusCode getter & setter thread-safe

- Package.swift
- Sources/WeatherSDK/models/SimpleYesNo.swift
- Sources/WeatherSDK/models/TypedYesNo.swift
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/EnumGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/IntEnumGenerator.kt
- smithy-swift-codegen/src/test/kotlin/EnumGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/IntEnumGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/ReservedWordsGeneratorTests.kt
https://github.com/awslabs/aws-sdk-swift/issues/1463
Removes the `.sdkUnknown()` case from the `allCases` property on both Int- & String-backed enums, because the case is not meaningful in the context of iterating or discovering the enum's cases.
> feat!: Remove unknown case from allCases in int & string enums

- .github/workflows/continuous-integration.yml
- Package.swift
- smithy-swift-codegen-test/smithy-build.json
https://github.com/awslabs/aws-sdk-swift/issues/1518
- Bump minimum Swift version from 5.7 to 5.9
- Update simulator versions
> chore!: Bump Swift minimum version & bump simulators in CI

- .github/workflows/continuous-integration.yml
https://github.com/awslabs/aws-sdk-swift/issues/1608
Disable forcing of Github Actions onto Node 20, since it does not work with Amazon Linux 2.
> chore: Allow old Node to be used on Linux CI

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolTestGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestErrorGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestRequestGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestResponseGenerator.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHTTPAWSJson11ProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHTTPEC2QueryProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHTTPRestJsonProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/mocks/MockHTTPRestXMLProtocolGenerator.kt
- Removes dead code associated with setting up the now-unused middleware stack for protocol tests
- Prevents two warnings per test for unused local vars by deleting them
- Extracts & simplifies some logic for rendering header expectations
- Remove other unused variables & functions
- General code cleanup
> chore: Remove unused code, refactor in protocol tests

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/serde/member/MemberShapeDecodeGenerator.kt
https://github.com/awslabs/aws-sdk-swift/issues/1622
To render the default value for an enum, an enum member matching the default value is located, then it is rendered as an enum case using the same logic as the enum definition.  See the [Smithy docs](https://smithy.io/2.0/spec/type-refinement-traits.html#default-value-constraints) for more details on how to interpret enum default values.
Enum default values have previously worked, even though the logic was incorrect, because enum values tend to closely resemble the enum member names.  This fixes a compile error introduced with the AWS Q Apps service, which uses enum values that are unlike the member names.
> fix: Render enum default values correctly

- Package.swift
- Tests/SmithyRetriesTests/RetryIntegrationTests.swift
SmithyRetriesTests test target was accidentally removed from Package.swift in #692, so this commit adds it back. The test was also not working properly, because Context.partitionID's attribute key name used by RetryMiddleware was different from the one being set in the test. This caused the test to exit early when partitionID wasn't found.
> fix: run retry integration tests

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareExecutionGenerator.kt
- smithy-swift-codegen/src/test/kotlin/EventStreamTests.kt
- smithy-swift-codegen/src/test/kotlin/HttpProtocolClientGeneratorTests.kt
https://github.com/awslabs/aws-sdk-swift/issues/1681
Preview builds are failing (on a compiler crash) while type checking the expression:
```swift
config.httpInterceptorProviders.forEach { provider in
let i: any ClientRuntime.HttpInterceptor<ListApplicationInstancesInput, ListApplicationInstancesOutput> = provider.create()
builder.interceptors.add(i)
}
```
This PR adds explicit type info to the `forEach` body, attempting to aid in type checking:
```swift
config.httpInterceptorProviders.forEach { (provider: any ClientRuntime.HttpInterceptorProvider) -> Void in
let i: any ClientRuntime.HttpInterceptor<ListApplicationInstancesInput, ListApplicationInstancesOutput> = provider.create()
builder.interceptors.add(i)
}
```
By submitting this pull request, I confirm that my contribution is made …
> fix: Supply explicit type on `forEach` block to try preventing compiler crash

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareExecutionGenerator.kt
- smithy-swift-codegen/src/test/kotlin/EventStreamTests.kt
- smithy-swift-codegen/src/test/kotlin/HttpProtocolClientGeneratorTests.kt
`meterScope` and `tracerScope` would be used in any library exporter of observability
> fix: codegen for orchestrator telemetry

- Sources/SmithyEventStreams/DefaultMessageDecoderStream.swift
- Sources/SmithyEventStreams/DefaultMessageEncoderStream.swift
- Sources/SmithyEventStreamsAPI/Header.swift
- Sources/SmithyEventStreamsAPI/Message.swift
https://github.com/awslabs/aws-sdk-swift/issues/1697
Fix code indentation where it was left with previous indenting during modularization.
No changes in this PR other than deleting indentation-related comments and changing leading whitespace.
Might be easier to review this with the "hide whitespace" diff feature enabled:
https://github.com/smithy-lang/smithy-swift/pull/804/files?diff=unified&w=1
> chore: Fix indentation of code after modularization

- Sources/ClientRuntime/Interceptor/HttpInterceptorProvider.swift
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/middleware/MiddlewareExecutionGenerator.kt
- smithy-swift-codegen/src/test/kotlin/EventStreamTests.kt
- smithy-swift-codegen/src/test/kotlin/HttpProtocolClientGeneratorTests.kt
https://github.com/awslabs/aws-sdk-swift/issues/1681
Change construction of HTTP interceptors to match non-HTTP, which is never flagged in compiler crashes.
This is an attempt to address compiler crashes on the automated build system.
> fix: Streamline HttpInterceptor type inference

- .github/workflows/continuous-integration.yml
https://github.com/awslabs/aws-sdk-swift/issues/1757
Runs Swift 6.0 as max supported Swift on Linux builds.
> chore: Run Linux CI on Swift 6.0

- .github/workflows/continuous-integration.yml
The downstream jobs currently run only unit tests, not protocol tests.  Likely protocol tests were dropped when they were split from the SDK's main package.swift to their own manifest.
Restore protocol tests during downstream jobs, to better test for regressions.
> chore: Run protocol tests with downstream CI builds

- Package.swift
- Sources/SmithyTestUtil/NetworkingTestUtils.swift
- Tests/SmithyHTTPAPITests/HttpStatusCodeTests.swift
I noticed that the `testHttpStatusCodeDescriptionWorks` unit test is located in `SmithyTestUtil`.  As a result, that test runs along with any set of unit tests that `SmithyTestUtil` is linked to.
Since the `HttpStatusCode` type is in the `SmithyHTTPAPI` module, I have created a `SmithyHTTPAPITests` test bundle and placed that test there, which is the correct place for that test to be located.
> chore: Move HTTP status code test out of SmithyTestUtil

- .github/workflows/continuous-integration.yml
- Package.swift
- Sources/SmithyTestUtil/DummyIdentityResolver.swift
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolUnitTestRequestGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/swiftmodules/SmithyIdentityTypes.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/swiftmodules/SmithyTestUtilTypes.kt
Companion `aws-sdk-swift` PR: https://github.com/awslabs/aws-sdk-swift/pull/1784
Protocol tests are now generated with static, dummy credentials which allow the test to succeed no matter what credentials (or no credentials at all) are configured on the test host system.  This will simplify test setup on CI & build systems, and allow us to run protocol tests on sandboxed platforms without special config.
- `SmithyTestUtil` now has a function which creates a static identity resolver with dummy AWS credentials.
- Request protocol tests are generated with client config that injects these static credentials.
- Client config codegen is also cleaned up by setting all client config fields at initialization.
By submitting this pull request, I confirm that my contribution is made under the terms of …
> chore: Protocol tests set their own AWS credentials

- .github/workflows/continuous-integration.yml
Github intends to remove Xcode 16 from the `macos-14` CI runner on Oct. 28:
https://github.com/actions/runner-images/issues/10703
Accordingly, we need to move our Xcode 16-based builds onto the `macos-15` CI runner by that date.
Per the reference above, the `macos-13` runner will remain unchanged so no need to change our builds that run there.
This PR updates Xcode 16 builds to use the `macos-15` runner instead of `macos-14`.
> chore: Run macOS 15 with Xcode 16 on CI

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/events/MessageMarshallableGenerator.kt
- smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/requestandresponse/EventStreamTests.kt
Quiets a warning that occurs when an event to be marshalled is unwrapped but not accessed.
Also adds some comments to help clear up what's going on in the `marshal` generated code.
> fix: Don't unwrap unneeded value during event marshal

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/AuthSchemeResolverGenerator.kt
Add `SESv2` to the services that use rules-based auth.
> feat: Enable rules-based auth for SESv2 service

- Package.swift
- Sources/SmithyChecksums/CRC64NVME.swift
- Sources/SmithyChecksums/ChecksumAlgorithm.swift
- Sources/SmithyChecksumsAPI/Checksum.swift
- Sources/SmithyChecksumsAPI/ChecksumAlgorithm.swift
Companion PR: https://github.com/awslabs/aws-sdk-swift/pull/1801
- Bump aws-crt-swift version to 0.37.0 
- Add wrapper for new checksum algorithm CRC64-NVME
> feat!: Bump CRT version to 0.37.0 & add CRC64NVME checksum algorithm wrapper

- .github/workflows/continuous-integration.yml
- Use macOS 14 instead of 13 for min Xcode
- Use macOS 15 + Xcode 16.1 for max Xcode
- Run tests on visionOS as well as iOS & tvOS
Note: all workflow config in this PR is just copied from the same section in https://github.com/awslabs/aws-sdk-swift/pull/1807
> chore: Run Xcode 16.1 as latest Xcode on CI

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/httpResponse/HTTPResponseBindingErrorGenerator.kt
Related to https://github.com/awslabs/aws-sdk-swift/pull/1810
SWIFT-1865
- Make an operation's baseError query compatible if the service is marked with awsQueryCompatible trait
> feat: add support for awsQueryCompatible trait

- Sources/ClientRuntime/Orchestrator/Orchestrator.swift
- Tests/ClientRuntimeTests/OrchestratorTests/OrchestratorTests.swift
This change ensures that retry is only used when a request body is reusable, and that the request body is prepared for reuse if needed.
- When a request body is a seekable stream, rewind the stream to the beginning before retrying.  Do not retry if rewind is not successful.
- When a request body is a non-seekable stream, do not attempt to retry; fail the request immediately instead.
- Non-streamed request bodies (i.e. in-memory Data and empty bodies) are always retryable.
Additionally, unit tests are added to `Orchestrator` to verify correct retry behavior.
> fix: Retry handling for streamed request bodies

- Sources/ClientRuntime/Retries/DefaultRetryErrorInfoProvider.swift
- Tests/SmithyRetriesTests/DefaultRetryErrorInfoProviderTests.swift
URLSession will throw this error on connection timeout:
```
Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." 
```
Retry it as a transient error.
Also: remove support for the `retry-after` header, which was previously removed from the SDK.
> fix: Retry URLSession timeout error

- Sources/SmithyStreams/StreamableHttpBody.swift
- Tests/ClientRuntimeTests/NetworkingTests/Streaming/StreamableHttpBodyTests.swift
https://github.com/awslabs/aws-sdk-swift/issues/1824
- Fix the calculation of the number of bytes to read so that it is correct when Data is not zero-indexed (i.e. when it is "sliced" from a parent Data)
- Add tests to show that sliced data can be streamed
> fix: StreamableHttpBody streams sliced Data correctly

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ShapeValueGenerator.kt
- smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/codegencomponents/ShapeValueGeneratorTest.kt
SDK CI PR for changes in this PR: https://github.com/awslabs/aws-sdk-swift/pull/1826
- The `ShapeValueGenerator` is used to codegen input parameters for an input struct in protocol test codegen and smoke test codegen. `ShapeValueGenerator` currently only handles `epoch-seconds` (aka Unix time) timestamp format. This PR adds support for `date-time` as defined by RFC3339.
> fix: Add date-time timestamp handling to ShapeValueGenerator

- .github/workflows/continuous-integration.yml
[Github Runner v2.321.0](https://github.com/actions/runner/releases/tag/v2.321.0) removed Node 16.  Since AL2 is not compatible with Node 20 due to the glibc version it uses, several important Github Actions may no longer run on AL2.
This PR disables CI on AL2.  Linux is still covered by running Ubuntu tests.  It is likely that we will not be able to test Amazon Linux on Github again until Swift adopts a newer version of Amazon Linux, i.e. 2023.
> chore: Disable Github CI on Amazon Linux 2

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/config/ConfigProperty.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolServiceClient.kt
- smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/HttpProtocolClientGeneratorTests.kt
- Reformat params for client config initializers so they are one per line
- Some other light cleanup / whitespace changes
The generated codegen changes are in code formatting only.  See the changes in the codegen test file diff to see the specific effect of this PR on generated code.
> chore: Clean up client config codegen

- Package.swift
- New v0.40.0 of aws-crt-swift fixes a bug with the underlying sts assume role credentials provider where initialization would throw error due to missing bootstrap argument. Link to release: https://github.com/awslabs/aws-crt-swift/releases/tag/v0.40.0
> chore: Bump aws-crt-swift version to 0.40.0

- .github/workflows/repo-sync.yml
1934
- Adds a GitHub workflow that syncs staging repo's main branch with public repo's main branch on either of these conditions:
- A new commit is made to public repo's main branch
- It's triggered manually via GitHub UI
> chore: Repo sync GH workflow

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ServiceGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpProtocolClientGenerator.kt
- https://github.com/awslabs/aws-sdk-swift/issues/1849
- Fixes where the name for the service in operation docs in API reference doc is sourced from 
> fix: Fix service name rendered on API reference docs

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/StructureGenerator.kt
- smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/ServiceRenamesTests.kt
- smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/basicshapes/StructEncodeGenerationIsolatedTests.kt
- smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/basicshapes/StructureGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/codegencomponents/RecursiveShapeBoxerTests.kt
- smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/protocolspecificserde/awsjson11/NestedListEncodeJSONGenerationTests.kt
Fixes formatting of generated structures so that the closing parenthesis of the `init` params and the opening curly brace of the `init` body are on the same line.
> fix: Proper formatting of generated structures

- Sources/SmithyJSON/Reader/Reader.swift
- Tests/SmithyJSONTests/FloatingPointTests.swift
Sometimes when JSON floating point numbers with many decimal places are read, Framework's `NSJSONSerialization` parser passes them to us as `NSDecimalNumber`, a subclass of `NSNumber`.  `NSDecimalNumber` seems to have some sort of bug where its `doubleValue` property is not always accurate in the least significant digits, although the stored decimal number is correct.
This PR fixes the issue by converting the decimal value of the `NSDecimalNumber` to string, then converting the string to a `Double`.  There is a performance penalty associated with this conversion, but it does appear to be correct.
Tests are added to verify that the issue is resolved.  Tests were performed for `Float` as well as for `Double`, and it appears that only `Double` is affected.
By submitting this pull request, I …
> fix: Doubles lose precision when read from JSON

- Sources/SmithyStreams/FileStream.swift
AWS SDK CI PR: https://github.com/awslabs/aws-sdk-swift/pull/1888
N/A 
- If the `FileHandle` provided to `FileStream` initializer points to a large file, say a 5TB file, program crashes due to out of memory exception because the initializer fetches the entire available data of the file just to get the current position of the provided file handle. Instead, just use the `offsetInFile` property.
> fix: Fix FileStream initializer that causes out of memory exception

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HTTPBindingProtocolGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/protocols/rpcv2cbor/RpcV2CborProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/protocolgeneratormocks/MockHTTPAWSJson11ProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/protocolgeneratormocks/MockHTTPEC2QueryProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/protocolgeneratormocks/MockHTTPRPCv2CBORProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/protocolgeneratormocks/MockHTTPRestJsonProtocolGenerator.kt
- smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/protocolgeneratormocks/MockHTTPRestXMLProtocolGenerator.kt
- `HTTPBindingProtocolGenerator` has a new, abstract method `httpBodyMembers()` that can be precisely defined by each Smithy protocol.
- RPCv2CBOR & all the mock protocol generators define this method for their needs.
> fix: Allow customization of HTTP body members per-protocol

- Package.swift
Upgrade aws-crt-swift to [0.44.0](https://github.com/awslabs/aws-crt-swift/releases/tag/v0.44.0)
This version lifts the upper limit on event stream message size from 16MB to 256MB.
> chore: Update to aws-crt-swift 0.44.0

- Sources/ClientRuntime/Config/ClientConfigDefaultsProvider.swift
- Sources/ClientRuntime/Config/DefaultSDKRuntimeConfiguration.swift
Companion PR: https://github.com/awslabs/aws-sdk-swift/pull/1904
- Make HTTP client config default provider take in user-provided HTTP client config. Use default config only if user didn't provide any HTTP client config (determined by nil check).
- Also, misc. fix on CRT HTTP client init call indentation.
> fix: Make default HTTP client provider use the customer-provided config if present

- Sources/Smithy/Logging/LogAgent.swift
- Sources/Smithy/Logging/LogAgentLevel.swift
- Tests/ClientRuntimeTests/NetworkingTests/URLSession/FoundationStreamBridgeTests.swift
- Tests/ClientRuntimeTests/OrchestratorTests/OrchestratorTests.swift
Companion PR: https://github.com/awslabs/aws-sdk-swift/pull/1908
N/A
- Make `LogAgent` protocol conform to `Sendable`. This makes `SwiftLogger` struct `Sendable`, removing the need for `@preconcurrency` prefix for import when customers try to use the logger in concurrent context.
- Makes the test logger implementations with @unchecked Sendable; they contain mutable string array that stores logged messages for validating test results. Since tests don't need concurrency safety, just marked as unchecked.
> chore: Make LogAgent conform to Sendable

- Package.swift
Updates `aws-crt-swift` to 0.48.0
- enforces 24MB limit on streamed events
> chore: Update to aws-crt-swift 0.48.0

- Sources/ClientRuntime/Networking/Http/CRT/CRTClientEngine.swift
CI PR in SDK: https://github.com/awslabs/aws-sdk-swift/pull/1919
N/A
- Bug found as part of investigating why the integration test in the PR https://github.com/awslabs/aws-sdk-swift/pull/1917 throws an error in CRT HTTP client but doesn't fail the test case.
- Ran the same integ test with the change in this PR and error gets thrown up and fails the test case as expected.
> fix: Fix silent failure with CRT HTTP client when response stream has an error

- Sources/ClientRuntime/Networking/Http/CRT/CRTClientEngine.swift
- Sources/Smithy/URI.swift
- Sources/SmithyHTTPAPI/Endpoint.swift
- Sources/SmithyHTTPAPI/HTTPRequest.swift
- Sources/SmithyTestUtil/RequestTestUtil/ExpectedSdkHttpRequest.swift
[BREAKING] Changes the type for port number from `Int16` to `UInt16`.  TCP port may be from 0-65535 which is beyond the range of `Int16`.
This affects public interfaces for URI, Endpoint, HTTPRequest, and their associated builder types.
The change is breaking because port number is exposed as a property of several public types and parameters to public functions.  The change is being made nonetheless because it is a significant impediment to not allow use of all possible TCP ports.
> fix!: Represent TCP port as UInt16

- Sources/SmithyStreams/StreamableHttpBody.swift
aws-sdk-swift PR for running integ tests against this change: 
- https://github.com/awslabs/aws-sdk-swift/pull/1935
N/A
- Fixes a bug where chunked streaming Data payload gets cut prematurely due to wrong isEndOfStream implementation
> fix: Fix StreamableHttpBody's isEndOfStream bug

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/waiters/WaiterAcceptorGenerator.kt
https://github.com/awslabs/aws-sdk-swift/issues/1981
Fixes a bug where the `ALL_STRING_EQUALS` string matcher fails when there is one element in a list of Strings.
> fix: ANY_STRING_EQUALS waiter matcher match on one string

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/AuthSchemeResolverGenerator.kt
- smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/requestandresponse/requestflow/AuthSchemeResolverGeneratorTests.kt
**Breaking Change**: Removed authSchemePreference from the default auth scheme resolver initializer.
Bug Fix: authSchemePreference will now operate as expected when passed into the service config
> fix: authSchemePreference in config + remove from default resolver

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/DependencyJSONGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/PackageManifestGenerator.kt
- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/SwiftDependency.kt
- smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/manifestanddocs/DependencyJSONGeneratorTests.kt
- smithy-swift-codegen/src/test/kotlin/software/amazon/smithy/swift/codegen/manifestanddocs/PackageManifestGeneratorTests.kt
Removes the `DistributionMethod` type because it was only needed for Swift Package Registry.  Simplified code that used to handle distribution method.
> chore: Remove package scope property

- .github/workflows/continuous-integration.yml
Runs smithy-swift latest CI on Xcode 26, and using iOS 26 / tvOS 26 / visionOS 26 sims.  All "26" versions are currently pre-release beta versions.
Changes are copied in from PR https://github.com/awslabs/aws-sdk-swift/pull/2016.
> chore: Run latest CI on Xcode 26

- .github/workflows/continuous-integration.yml
Use Swift 6.2 as the latest Linux image for CI & integration tests.
> chore: Use Swift 6.2 as Linux latest

- Sources/ClientRuntime/Networking/Http/NIO/NIOHTTPClientError.swift
- Sources/ClientRuntime/Networking/Http/NIO/NIOHTTPClientStreamBridge.swift
- Tests/ClientRuntimeTests/NetworkingTests/Http/NIO/NIOHTTPClientStreamBridgeTests.swift
> add initial stream bridge

- smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/ServiceGenerator.kt
Corrects the `input` param description in documentation comments for operations, so that the doc comment renders in Xcode/docc correctly.
Example diff:
```
-    /// - Parameter CreateApiKeyInput : Request to create an ApiKey resource.
+    /// - Parameter input: Request to create an ApiKey resource. (Type: `CreateApiKeyInput`)
///
-    /// - Returns: `CreateApiKeyOutput` : A resource that can be distributed to callers for executing Method resources that require an API key. API keys can be
mapped to any Stage on any RestApi, which indicates that the callers with the API key can make requests to that stage.
+    /// - Returns: A resource that can be distributed to callers for executing Method resources that require an API key. API keys can be mapped to any Stage on
any RestApi, which …
```
> fix: Fix input param syntax in operation doc comments
